# Generated by Django 5.1 on 2024-10-07 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snils', models.CharField(max_length=11, unique=True, verbose_name='СНИЛС')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телеграм')),
                ('citizenship', models.IntegerField(choices=[(1, 'РФ'), (2, 'Иностранец')], default=1, verbose_name='Гражданство')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='PostRG014',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код должности')),
                ('description', models.CharField(max_length=255, verbose_name='Наименование должности')),
            ],
            options={
                'verbose_name': 'Должность RG014',
                'verbose_name_plural': 'Справочник: Должности RG014',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код профиля')),
                ('description', models.CharField(max_length=255, verbose_name='Описание профиля')),
            ],
            options={
                'verbose_name': 'Профиль медицинской помощи',
                'verbose_name_plural': 'Справочник: Профили помощи',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код специальности')),
                ('description', models.CharField(max_length=255, verbose_name='Описание специальности')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Справочник: Специальности',
            },
        ),
        migrations.CreateModel(
            name='SpecialtyRG014',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код специальности')),
                ('description', models.CharField(max_length=255, verbose_name='Наименование специальности')),
            ],
            options={
                'verbose_name': 'Специальность RG014',
                'verbose_name_plural': 'Справочник: Специальности RG014',
            },
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(verbose_name='Действует по')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='Дата передачи врачу')),
                ('revoked_date', models.DateField(blank=True, null=True, verbose_name='Дата аннулирования')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_signatures', to='personnel.person')),
            ],
            options={
                'verbose_name': 'ЭЦП',
                'verbose_name_plural': 'ЭЦП',
            },
        ),
        migrations.CreateModel(
            name='DoctorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_code', models.CharField(max_length=20, verbose_name='Код врача')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала работы')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания работы')),
                ('structural_unit', models.CharField(default='-', max_length=255, verbose_name='Структурное подразделение')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department', verbose_name='Отделение')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_records', to='personnel.person', verbose_name='Физическое лицо')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.profile', verbose_name='Профиль медицинской помощи')),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Запись врача',
                'verbose_name_plural': 'Журнал врачей',
            },
        ),
        migrations.CreateModel(
            name='RG014',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_issue_date', models.DateField(verbose_name='Дата выдачи сертификата или аккредитации')),
                ('cert_accred_sign', models.IntegerField(choices=[(1, 'Сертификат'), (2, 'Аккредитация')], verbose_name='Признак сертификата или аккредитации')),
                ('hire_date', models.DateField(verbose_name='Дата приёма')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.medicalorganization', verbose_name='Медицинская организация')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rg014_records', to='personnel.person', verbose_name='Физическое лицо')),
                ('post_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.postrg014', verbose_name='Наименование должности')),
                ('spec_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.specialtyrg014', verbose_name='Наименование специальности')),
            ],
            options={
                'verbose_name': 'Запись RG014',
                'verbose_name_plural': 'Записи для RG014',
            },
        ),
    ]
