# Generated by Django 5.1 on 2024-12-03 12:57

import apps.personnel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalsignature',
            name='added_at',
            field=models.DateTimeField(default='2020-01-01', verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to=apps.personnel.models.digital_signature_upload_path, verbose_name='Скан ЭЦП'),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='scan_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата загрузки скана'),
        ),
    ]
