# Generated by Django 5.1 on 2024-12-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_digitalsignature_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalsignature',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Действует с'),
        ),
        migrations.AlterField(
            model_name='digitalsignature',
            name='valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='Действует по'),
        ),
    ]
