# Generated by Django 5.1 on 2024-12-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_alter_digitalsignature_valid_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalsignature',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='application_date',
            field=models.DateField(blank=True, default='2020-01-01', null=True, verbose_name='Действует с'),
        ),
    ]
