# Generated by Django 5.1 on 2024-12-03 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_remove_digitalsignature_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalsignature',
            name='application_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заявления'),
        ),
        migrations.CreateModel(
            name='MaternityLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала декрета')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания декрета')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maternity_leaves', to='personnel.person', verbose_name='Физическое лицо')),
            ],
            options={
                'verbose_name': 'Декрет',
                'verbose_name_plural': 'Декреты',
                'ordering': ['start_date'],
            },
        ),
    ]
