# Generated by Django 5.1 on 2025-02-10 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_station_doctorassignment'),
        ('personnel', '0006_alter_digitalsignature_application_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReportingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала включения в отчеты')),
                ('end_date', models.DateField(blank=True, help_text='Если не указано, считается без ограничения по дате', null=True, verbose_name='Дата окончания включения в отчеты')),
                ('fte', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Ставка (FTE)')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department', verbose_name='Отделение')),
                ('doctor_records', models.ManyToManyField(related_name='reporting_records', to='personnel.doctorrecord', verbose_name='Записи врача (DoctorRecord)')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.person', verbose_name='Физическое лицо')),
            ],
            options={
                'verbose_name': 'Запись для отчётности врача',
                'verbose_name_plural': 'Записи для отчётности врачей',
            },
        ),
    ]
