# Generated by Django 5.1 on 2025-02-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_doctorreportingrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorreportingrecord',
            name='doctor_records',
            field=models.ManyToManyField(blank=True, related_name='reporting_records', to='personnel.doctorrecord', verbose_name='Записи врача (DoctorRecord)'),
        ),
    ]
