# Generated by Django 5.1 on 2025-03-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_telegrambot_telegramgroup'),
        ('personnel', '0010_alter_person_options_alter_postrg014_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='telegram_groups',
            field=models.ManyToManyField(blank=True, related_name='persons', to='home.telegramgroup', verbose_name='Телеграм группы'),
        ),
    ]
