# Generated by Django 5.1 on 2025-03-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0011_person_telegram_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='telegram_signature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись для Telegram'),
        ),
    ]
