# Generated by Django 5.1 on 2025-03-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_person_telegram_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='telegram_signature',
        ),
    ]
