# Generated by Django 5.1 on 2025-03-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0013_remove_person_telegram_signature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Физическое лицо', 'verbose_name_plural': 'Физические лица'},
        ),
    ]
