# Generated by Django 5.1 on 2025-04-08 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_station_doctorassignment'),
        ('personnel', '0014_alter_person_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала работы')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания работы')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department', verbose_name='Отделение')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_record', to='personnel.person')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personnel.postrg014', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Запись сотрудника',
                'verbose_name_plural': 'Записи сотрудников',
            },
        ),
    ]
