# Generated by Django 5.1 on 2025-04-08 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0015_staffrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrecord',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_records', to='personnel.person'),
        ),
    ]
