# Generated by Django 5.1 on 2025-04-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0016_alter_staffrecord_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffrecord',
            options={'verbose_name': 'Запись сотрудника', 'verbose_name_plural': 'Записи сотрудника'},
        ),
    ]
