# Generated by Django 5.1 on 2025-03-20 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp', models.CharField(max_length=255, unique=True, verbose_name='Единый номер полиса')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('dr', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=50, verbose_name='PID')),
                ('ldwid', models.CharField(max_length=50, verbose_name='LDWID')),
                ('ds', models.CharField(max_length=255, verbose_name='Диагноз')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='dn_app.person')),
            ],
            options={
                'unique_together': {('person', 'ldwid', 'ds')},
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdwid', models.CharField(max_length=50, verbose_name='PDWID')),
                ('plan_month', models.CharField(blank=True, max_length=10, null=True, verbose_name='Плановый месяц')),
                ('plan_year', models.CharField(blank=True, max_length=10, null=True, verbose_name='Плановый год')),
                ('date_begin', models.DateField(blank=True, null=True, verbose_name='Дата начала наблюдения')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания наблюдения')),
                ('effective_from', models.DateTimeField(auto_now_add=True, verbose_name='Начало действия')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='Окончание действия')),
                ('is_current', models.BooleanField(default=True, verbose_name='Актуально')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='dn_app.encounter')),
            ],
            options={
                'unique_together': {('encounter', 'pdwid', 'effective_from')},
            },
        ),
    ]
