# Generated by Django 5.1 on 2026-02-18 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('year', models.IntegerField(verbose_name='Год данных')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к файлу')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Всего строк в файле')),
                ('processed_rows', models.IntegerField(default=0, verbose_name='Обработано строк')),
                ('created_persons', models.IntegerField(default=0, verbose_name='Создано пациентов')),
                ('updated_persons', models.IntegerField(default=0, verbose_name='Обновлено пациентов')),
                ('created_encounters', models.IntegerField(default=0, verbose_name='Создано встреч')),
                ('created_observations', models.IntegerField(default=0, verbose_name='Создано наблюдений')),
                ('detached_patients', models.IntegerField(default=0, verbose_name='Откреплено пациентов')),
                ('status', models.CharField(choices=[('processing', 'Обработка'), ('completed', 'Завершено'), ('error', 'Ошибка')], default='processing', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Загрузка данных',
                'verbose_name_plural': 'Загрузки данных',
                'ordering': ['-import_date'],
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='actual_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата фактического посещения'),
        ),
        migrations.AddField(
            model_name='observation',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирован'), ('completed', 'Выполнен'), ('not_completed', 'Не выполнен'), ('detached', 'Откреплен')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='observation',
            name='talon_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер талона ОМС'),
        ),
        migrations.AddField(
            model_name='person',
            name='detached_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата открепления'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_detached',
            field=models.BooleanField(default=False, help_text='Пациент откреплен (отсутствует в последней загрузке)', verbose_name='Откреплен'),
        ),
        migrations.AddField(
            model_name='person',
            name='last_import_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней загрузки'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='plan_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Плановый год'),
        ),
        migrations.AddField(
            model_name='observation',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='dn_app.dataimport'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['plan_year', 'status'], name='dn_app_obse_plan_ye_cafd80_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['plan_year', 'is_current'], name='dn_app_obse_plan_ye_bdf4f8_idx'),
        ),
    ]
