# Generated by Django 5.1 on 2026-08-26 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn_app', '0002_dataimport_observation_actual_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp', models.CharField(db_index=True, max_length=255, verbose_name='ЕНП')),
                ('ds_code', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Код МКБ')),
                ('report_year', models.IntegerField(db_index=True, verbose_name='Год')),
                ('source', models.CharField(choices=[('oms', 'ОМС талон'), ('kvazar', 'Квазар журнал ДН')], db_index=True, max_length=16)),
                ('talon', models.CharField(blank=True, default='', max_length=64, verbose_name='Номер талона')),
                ('goal', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Цель')),
                ('treatment_end', models.CharField(blank=True, default='', max_length=32, verbose_name='Дата окончания')),
                ('status', models.CharField(blank=True, default='', max_length=64, verbose_name='Статус талона')),
                ('doctor', models.CharField(blank=True, default='', max_length=255, verbose_name='Врач')),
                ('raw_diagnosis', models.CharField(blank=True, default='', max_length=512, verbose_name='Диагноз сырой')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Факт ДН',
                'verbose_name_plural': 'Факты ДН',
            },
        ),
        migrations.CreateModel(
            name='DnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdwid', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='pdwID')),
                ('pid', models.CharField(blank=True, default='', max_length=50, verbose_name='pID')),
                ('ldwid', models.CharField(blank=True, default='', max_length=50, verbose_name='ldwID')),
                ('ds', models.CharField(blank=True, default='', max_length=255, verbose_name='Диагноз (сырой)')),
                ('ds_code', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Код МКБ')),
                ('date_begin', models.DateField(blank=True, null=True, verbose_name='Поставлен на ДН')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Снят с ДН')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Причина снятия')),
                ('plan_year', models.IntegerField(db_index=True, verbose_name='Плановый год')),
                ('plan_month', models.CharField(blank=True, default='', max_length=10, verbose_name='Плановый месяц')),
                ('doctor', models.CharField(blank=True, default='', max_length=255, verbose_name='Врач ДН')),
                ('specialty_raw', models.CharField(blank=True, default='', max_length=255, verbose_name='Специальность (сырая)')),
                ('category_168n', models.CharField(blank=True, db_index=True, default='', help_text='БСК / ОНКО / СД / Прочие', max_length=64, verbose_name='Категория 168н')),
                ('profile_cluster', models.CharField(blank=True, db_index=True, default='', help_text='Терапия (ВОП/терапия/леч.дело) и др.', max_length=128, verbose_name='Профиль (кластер)')),
                ('out_of_168n', models.BooleanField(db_index=True, default=False, help_text='МКБ нет в справочнике → кандидат на цель 305', verbose_name='Вне 168н')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('completed', 'Выполнен'), ('not_completed', 'Не выполнен'), ('detached', 'Откреплен / снят')], db_index=True, default='planned', max_length=20)),
                ('is_current', models.BooleanField(db_index=True, default=True, verbose_name='Актуально в снимке года')),
                ('talon_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Талон ОМС')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Дата факта')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Линия ДН',
                'verbose_name_plural': 'Линии ДН',
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Пациент ДН', 'verbose_name_plural': 'Пациенты ДН'},
        ),
        migrations.AddField(
            model_name='person',
            name='lpuuch',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dr',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_detached',
            field=models.BooleanField(default=False, help_text='Пациент откреплен (отсутствует в последней загрузке текущего года)', verbose_name='Откреплен'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['fio'], name='dn_app_pers_fio_392624_idx'),
        ),
        migrations.AddField(
            model_name='dnfact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dn_facts', to='dn_app.person'),
        ),
        migrations.AddField(
            model_name='dnline',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dn_lines', to='dn_app.dataimport'),
        ),
        migrations.AddField(
            model_name='dnline',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dn_lines', to='dn_app.person'),
        ),
        migrations.AddIndex(
            model_name='dnfact',
            index=models.Index(fields=['enp', 'ds_code', 'report_year'], name='dn_app_dnfa_enp_ae6e44_idx'),
        ),
        migrations.AddIndex(
            model_name='dnfact',
            index=models.Index(fields=['report_year', 'source', 'goal'], name='dn_app_dnfa_report__65d9f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='dnfact',
            constraint=models.UniqueConstraint(fields=('source', 'enp', 'ds_code', 'report_year', 'talon'), name='dn_fact_uniq_source_enp_ds_year_talon'),
        ),
        migrations.AddIndex(
            model_name='dnline',
            index=models.Index(fields=['plan_year', 'is_current'], name='dn_app_dnli_plan_ye_54201a_idx'),
        ),
        migrations.AddIndex(
            model_name='dnline',
            index=models.Index(fields=['plan_year', 'status'], name='dn_app_dnli_plan_ye_4298ff_idx'),
        ),
        migrations.AddIndex(
            model_name='dnline',
            index=models.Index(fields=['person', 'ds_code'], name='dn_app_dnli_person__9b5f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='dnline',
            index=models.Index(fields=['plan_year', 'category_168n'], name='dn_app_dnli_plan_ye_daa343_idx'),
        ),
        migrations.AddIndex(
            model_name='dnline',
            index=models.Index(fields=['plan_year', 'out_of_168n'], name='dn_app_dnli_plan_ye_3924d1_idx'),
        ),
    ]
