# Generated by Django 5.1 on 2025-05-28 11:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MKB10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Код должен соответствовать формату МКБ-10 (например: A01.1)', regex='^[A-Z]\\d{2}(\\.\\d{1,2})?$')], verbose_name='Код МКБ-10')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень иерархии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание/Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='references.mkb10', verbose_name='Родительский код')),
            ],
            options={
                'verbose_name': 'МКБ-10: диагноз',
                'verbose_name_plural': 'МКБ-10: диагнозы',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='references__code_d40af6_idx'), models.Index(fields=['is_active'], name='references__is_acti_16515c_idx')],
                'unique_together': {('code', 'parent')},
            },
        ),
    ]
