# Generated by Django 5.1 on 2025-05-28 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mkb10',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='Конечный диагноз'),
        ),
        migrations.AlterField(
            model_name='mkb10',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
