# Generated by Django 5.1 on 2025-06-23 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_mkb10_is_final_alter_mkb10_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf_okato', models.CharField(max_length=5, verbose_name='ОКАТО')),
                ('smocod', models.CharField(max_length=5, verbose_name='Код СМО')),
                ('nam_smop', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('nam_smok', models.CharField(max_length=255, verbose_name='Краткое наименование')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=13, verbose_name='ОГРН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('jur_address_index', models.CharField(max_length=6, verbose_name='Индекс юр. адреса')),
                ('jur_address', models.TextField(verbose_name='Юридический адрес')),
                ('pst_address_index', models.CharField(max_length=6, verbose_name='Индекс почт. адреса')),
                ('pst_address', models.TextField(verbose_name='Почтовый адрес')),
                ('okopf', models.CharField(max_length=5, verbose_name='ОКОПФ')),
                ('head_lastname', models.CharField(max_length=100, verbose_name='Фамилия руководителя')),
                ('head_firstname', models.CharField(max_length=100, verbose_name='Имя руководителя')),
                ('head_middlename', models.CharField(max_length=100, verbose_name='Отчество руководителя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('fax', models.CharField(max_length=20, verbose_name='Факс')),
                ('hot_line', models.CharField(max_length=20, verbose_name='Горячая линия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('license_number', models.CharField(max_length=20, verbose_name='Номер лицензии')),
                ('license_start_date', models.DateField(verbose_name='Дата начала лицензии')),
                ('license_end_date', models.DateField(verbose_name='Дата окончания лицензии')),
                ('org_type', models.CharField(max_length=2, verbose_name='Тип организации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_default', models.BooleanField(default=False, verbose_name='СМО по умолчанию')),
                ('year_work', models.IntegerField(verbose_name='Год работы')),
                ('last_update', models.DateField(verbose_name='Дата последнего обновления')),
                ('insured_count', models.IntegerField(verbose_name='Количество застрахованных')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Страховая медицинская организация',
                'verbose_name_plural': 'Страховые медицинские организации',
                'ordering': ['nam_smok'],
                'indexes': [models.Index(fields=['smocod'], name='references__smocod_355e71_idx'), models.Index(fields=['inn'], name='references__inn_eca39e_idx'), models.Index(fields=['is_active'], name='references__is_acti_c9039e_idx'), models.Index(fields=['is_default'], name='references__is_defa_0539b4_idx')],
            },
        ),
    ]
