# Generated by Django 5.1 on 2024-10-07 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название корпуса')),
                ('additional_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительное название корпуса')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпусы',
            },
        ),
        migrations.CreateModel(
            name='MedicalOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('name_kvazar', models.CharField(max_length=255, verbose_name='Название организации в Квазар')),
                ('name_miskauz', models.CharField(max_length=255, verbose_name='Название организации в КАУЗ')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('code_mo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код МО в СМО')),
            ],
            options={
                'verbose_name': 'Медицинскую организацию',
                'verbose_name_plural': 'Медицинская организация',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отделения')),
                ('additional_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительное название отделения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.building', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='organization.medicalorganization', verbose_name='Организация'),
        ),
    ]
