# Generated by Django 5.1 on 2024-10-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='name_kvazar',
            field=models.CharField(default=1, max_length=255, verbose_name='Название корпуса в Квазар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='name_miskauz',
            field=models.CharField(default=100, max_length=255, verbose_name='Название корпуса в КАУЗ'),
            preserve_default=False,
        ),
    ]
