# Generated by Django 5.1 on 2024-10-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_building_name_kvazar_building_name_miskauz'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalorganization',
            name='oid_mo',
            field=models.CharField(default=1, max_length=50, verbose_name='OID МО'),
            preserve_default=False,
        ),
    ]
