# Generated by Django 5.1 on 2024-10-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_medicalorganization_oid_mo'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvazarDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отделения в Квазар')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kvazar_departments', to='organization.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Отделение Квазар',
                'verbose_name_plural': 'Отделения Квазар',
            },
        ),
        migrations.CreateModel(
            name='MiskauzDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отделения в МИСКАУЗ')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miskauz_departments', to='organization.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Отделение МИСКАУЗ',
                'verbose_name_plural': 'Отделения МИСКАУЗ',
            },
        ),
        migrations.CreateModel(
            name='OMSDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отделения в Web-ОМС')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oms_departments', to='organization.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Отделение Web-ОМС',
                'verbose_name_plural': 'Отделения Web-ОМС',
            },
        ),
    ]
