# Generated by Django 5.1 on 2024-10-29 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_kvazardepartment_miskauzdepartment_omsdepartment'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код участка')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название участка')),
                ('open_date', models.DateField(blank=True, null=True, verbose_name='Дата введения участка')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='Дата закрытия участка')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='organization.department', verbose_name='Отделение')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='personnel.doctorrecord', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
            },
        ),
        migrations.CreateModel(
            name='DoctorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата назначения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения работы')),
                ('reason_for_transfer', models.TextField(blank=True, null=True, verbose_name='Причина перевода')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='personnel.doctorrecord', verbose_name='Врач')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='organization.station', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Назначение врача на участок',
                'verbose_name_plural': 'Назначения врачей на участки',
                'ordering': ['-start_date'],
            },
        ),
    ]
