# Generated by Django 5.1 on 2024-11-14 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('dr', models.CharField(max_length=255, verbose_name='Дата рождения')),
                ('enp', models.CharField(max_length=255, unique=True, verbose_name='ЕНП')),
                ('phone', models.CharField(default='-', max_length=255, verbose_name='Телефон')),
                ('address', models.CharField(default='-', max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='ISZLPeopleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_report', models.DateField(verbose_name='Дата отчета')),
                ('smo', models.CharField(max_length=255, verbose_name='СМО')),
                ('ss_doctor', models.CharField(max_length=255, verbose_name='Врач')),
                ('lpuuch', models.CharField(max_length=255, verbose_name='Участок')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.people', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Отчет по населению в ИСЗЛ',
                'verbose_name_plural': 'Отчеты по населению в ИСЗЛ',
            },
        ),
    ]
