# Generated by Django 5.1 on 2024-11-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISZLReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_report', models.DateField(unique=True, verbose_name='Дата отчета')),
                ('patient_count', models.IntegerField(verbose_name='Количество пациентов')),
                ('change', models.IntegerField(verbose_name='Изменение')),
            ],
        ),
    ]
