# Generated by Django 5.1 on 2026-08-28 07:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код издания')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('archived', 'Архив')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('max_doctor_visits', models.PositiveSmallIntegerField(default=3, help_text='Сколько раз учитывается услуга «Диспансерный приём …» на талон: 1 — одна позиция в матрице до 01.04, 3 — по числу явок с 01.04.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Макс. явок к врачу (диспансерный приём)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Издание матрицы ДН',
                'verbose_name_plural': 'ДН: издания матрицы',
                'ordering': ['-effective_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DnDiagnosisCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, verbose_name='Код')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dn_matrix.dndiagnosiscategory', verbose_name='Родитель')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_categories', to='dn_matrix.matrixedition', verbose_name='Издание')),
            ],
            options={
                'verbose_name': 'Категория диагнозов',
                'verbose_name_plural': 'ДН: категории диагнозов',
                'ordering': ['sort_order', 'code'],
                'unique_together': {('edition', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DnDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mkb_code', models.CharField(db_index=True, max_length=16, verbose_name='Код МКБ')),
                ('title', models.CharField(max_length=512, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='dn_matrix.dndiagnosiscategory', verbose_name='Категория')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='dn_matrix.matrixedition', verbose_name='Издание')),
            ],
            options={
                'verbose_name': 'Диагноз (матрица ДН)',
                'verbose_name_plural': 'ДН: диагнозы',
                'ordering': ['mkb_code'],
                'unique_together': {('edition', 'mkb_code')},
            },
        ),
        migrations.CreateModel(
            name='DnSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, verbose_name='Код')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='dn_matrix.matrixedition', verbose_name='Издание')),
            ],
            options={
                'verbose_name': 'Специальность (матрица ДН)',
                'verbose_name_plural': 'ДН: специальности',
                'ordering': ['sort_order', 'code'],
                'unique_together': {('edition', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DnServicePricePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, verbose_name='Код периода')),
                ('title', models.CharField(blank=True, default='', max_length=256, verbose_name='Подпись')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_periods', to='dn_matrix.matrixedition', verbose_name='Издание')),
            ],
            options={
                'verbose_name': 'Период цен',
                'verbose_name_plural': 'ДН: периоды цен',
                'ordering': ['-valid_from', 'code'],
                'unique_together': {('edition', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DnService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Код услуги')),
                ('title', models.CharField(max_length=512, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('sex_restriction', models.CharField(blank=True, choices=[('', 'Любой'), ('M', 'Мужской'), ('F', 'Женский')], default='', max_length=1, verbose_name='Ограничение по полу')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='dn_matrix.matrixedition', verbose_name='Издание')),
            ],
            options={
                'verbose_name': 'Услуга (матрица ДН)',
                'verbose_name_plural': 'ДН: услуги',
                'ordering': ['sort_order', 'code'],
                'unique_together': {('edition', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DnDiagnosisGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, verbose_name='Код группы')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('rule', models.JSONField(blank=True, default=dict, verbose_name='Правило (расширение)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_groups', to='dn_matrix.matrixedition', verbose_name='Издание')),
            ],
            options={
                'verbose_name': 'Группа диагнозов',
                'verbose_name_plural': 'ДН: группы диагнозов',
                'ordering': ['sort_order', 'code'],
                'unique_together': {('edition', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DnDiagnosisGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='dn_matrix.dndiagnosis', verbose_name='Диагноз')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='dn_matrix.dndiagnosisgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Вхождение диагноза в группу',
                'verbose_name_plural': 'ДН: вхождения в группы',
                'unique_together': {('group', 'diagnosis')},
            },
        ),
        migrations.CreateModel(
            name='DnServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена')),
                ('currency', models.CharField(default='RUB', max_length=8, verbose_name='Валюта')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='dn_matrix.dnservice', verbose_name='Услуга')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='dn_matrix.dnservicepriceperiod', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Цена услуги',
                'verbose_name_plural': 'ДН: цены услуг',
                'unique_together': {('period', 'service')},
            },
        ),
        migrations.CreateModel(
            name='DnServiceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requirements', to='dn_matrix.dndiagnosis', verbose_name='Диагноз')),
                ('diagnosis_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requirements', to='dn_matrix.dndiagnosisgroup', verbose_name='Группа диагнозов')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='dn_matrix.dnservice', verbose_name='Услуга')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requirements', to='dn_matrix.dnspecialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Условие применимости услуги',
                'verbose_name_plural': 'ДН: условия применимости услуг',
                'constraints': [models.CheckConstraint(condition=models.Q(('specialty__isnull', False), ('diagnosis__isnull', False), ('diagnosis_group__isnull', False), _connector='OR'), name='dn_matrix_svc_req_non_empty_scope')],
            },
        ),
        migrations.CreateModel(
            name='DnDiagnosisSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('primary', 'Основная'), ('joint', 'Совместная'), ('accompanying', 'Сопутствующая')], default='primary', max_length=16, verbose_name='Тип связи')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_links', to='dn_matrix.dndiagnosis', verbose_name='Диагноз')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_links', to='dn_matrix.dnspecialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Диагноз — специальность',
                'verbose_name_plural': 'ДН: связи диагноз—специальность',
                'unique_together': {('diagnosis', 'specialty', 'kind')},
            },
        ),
    ]
