# Generated by Django 5.1 on 2026-08-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn_matrix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnUnavailableService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(db_index=True, help_text='Код из матрицы. Хранится строкой, чтобы список не стирался при повторном импорте пакета.', max_length=32, verbose_name='Код услуги')),
                ('mkb_code', models.CharField(blank=True, default='', help_text='Пусто — услуга не проводится при любом диагнозе. Иначе только для этого МКБ.', max_length=16, verbose_name='Код МКБ')),
                ('note', models.CharField(blank=True, default='', max_length=256, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_services', to='dn_matrix.matrixedition', verbose_name='Издание')),
            ],
            options={
                'verbose_name': 'Услуга, которая не проводится',
                'verbose_name_plural': 'ДН: услуги, которые не проводятся',
                'ordering': ['service_code', 'mkb_code'],
                'constraints': [models.UniqueConstraint(fields=('edition', 'service_code', 'mkb_code'), name='dn_matrix_unavail_ed_svc_mkb')],
            },
        ),
    ]
