# Generated by Django 5.1

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthSchool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveSmallIntegerField(unique=True, verbose_name="№")),
                ("name", models.CharField(max_length=256, verbose_name="Школа")),
                ("group_name", models.CharField(blank=True, default="", max_length=128, verbose_name="Группа")),
                ("mkb_rule", models.CharField(max_length=512, verbose_name="МКБ / критерий")),
                (
                    "visits",
                    models.PositiveSmallIntegerField(
                        default=4,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Явки",
                    ),
                ),
                ("duration", models.CharField(blank=True, default="", max_length=64, verbose_name="Длительность")),
                ("tariff", models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Тариф, руб.")),
                ("service_code", models.CharField(blank=True, default="", max_length=64, verbose_name="Код услуги")),
                (
                    "service_title",
                    models.CharField(blank=True, default="", max_length=512, verbose_name="Наименование услуги"),
                ),
                (
                    "period_years",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Повторное комплексное посещение этой школы не раньше чем через N лет. По умолчанию 3.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Периодичность, лет",
                    ),
                ),
                (
                    "criterion",
                    models.CharField(
                        choices=[
                            ("mkb", "МКБ"),
                            ("age", "Возраст"),
                            ("risk", "Фактор риска"),
                            ("bmi", "ИМТ / ожирение"),
                        ],
                        db_index=True,
                        default="mkb",
                        max_length=16,
                        verbose_name="Тип отбора",
                    ),
                ),
                ("min_age", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Мин. возраст")),
                ("max_age", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Макс. возраст")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Примечание")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="Активна")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Школа здоровья (307)",
                "verbose_name_plural": "Школы здоровья (307)",
                "ordering": ["number"],
            },
        ),
    ]
