# Generated by Django 5.1 on 2024-10-09 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Названия корпуса для группировки подразделений из Статистики Квазар')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
        migrations.CreateModel(
            name='FourteenDaysData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('subdivision', models.CharField(max_length=255)),
                ('speciality', models.CharField(max_length=255)),
                ('doctor_name', models.CharField(max_length=255)),
                ('reception_type', models.CharField(max_length=255)),
                ('total_slots', models.IntegerField()),
                ('epgu_slots', models.IntegerField()),
                ('free_slots', models.IntegerField()),
                ('free_epgu_slots', models.IntegerField()),
                ('report_datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Данные за 14 дней',
                'verbose_name_plural': 'Данные за 14 дней',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название из файла Статистики Квазар для фильтрации')),
                ('full_name', models.CharField(max_length=255, verbose_name='Название для отображения в заголовке дашборда')),
                ('logo', models.ImageField(upload_to='organization_logos/', verbose_name='Логотип')),
                ('background_color', models.CharField(default='#4c4bc0', max_length=7, verbose_name='Цвет фона сайта')),
                ('text_color', models.CharField(default='white', max_length=7, verbose_name='Цвет текста в таблицах и блоке header')),
                ('main_container_color', models.CharField(default='#1f2c56', max_length=7, verbose_name='Цвет фона контейнера с данными')),
                ('info_container_color', models.CharField(default='#1f2c56', max_length=7, verbose_name='Цвет фона контейнера с доп. информацией')),
                ('info_container_texy_color', models.CharField(default='#02ff35', max_length=7, verbose_name='Цвет текста контейнера с доп. информацией')),
                ('header_background_color', models.CharField(default='#3fa134', max_length=7, verbose_name='Цвет текста названий таблиц')),
                ('table_header_color', models.CharField(default='red', max_length=7, verbose_name='Цвет заголовков таблиц')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организация',
            },
        ),
        migrations.CreateModel(
            name='RegisteredPatients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=255)),
                ('slots_today', models.IntegerField()),
                ('free_slots_today', models.IntegerField()),
                ('slots_14_days', models.IntegerField()),
                ('free_slots_14_days', models.IntegerField()),
                ('report_datetime', models.CharField(default='-', max_length=50)),
            ],
            options={
                'verbose_name': 'Загруженные данные',
                'verbose_name_plural': 'Загруженные данные',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='TodayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('subdivision', models.CharField(max_length=255)),
                ('speciality', models.CharField(max_length=255)),
                ('doctor_name', models.CharField(max_length=255)),
                ('reception_type', models.CharField(max_length=255)),
                ('total_slots', models.IntegerField()),
                ('epgu_slots', models.IntegerField()),
                ('free_slots', models.IntegerField()),
                ('free_epgu_slots', models.IntegerField()),
                ('report_datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Данные за сегодня',
                'verbose_name_plural': 'Данные за сегодня',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок. Показывает то что будет написано в списке подразделений на главной странице')),
                ('path', models.CharField(max_length=100, unique=True, verbose_name='Путь отображаемый в браузерной ссылке на страницу(на английском)')),
                ('subdivision', models.CharField(max_length=100, verbose_name='Подпись на странице корпуса. Должно быть такое же как и в подключенном корпусе выше!')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='peopledash.building', verbose_name='Подключаем созданный корпус к страницу для отображения')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='peopledash.building')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
    ]
