# Generated by Django 5.1 on 2024-10-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dash_ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('dash_port', models.PositiveIntegerField(default='5000')),
                ('main_app_ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('main_app_port', models.PositiveIntegerField(default='8000')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
