# Generated by Django 5.1 on 2024-11-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='dash_chief_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='dash_chief_port',
            field=models.PositiveIntegerField(default='5010'),
        ),
    ]
