# Generated by Django 5.1 on 2024-11-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mainsettings_dash_chief_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='kauz_database_path',
            field=models.CharField(default='-', max_length=255, verbose_name='КАУЗ: Путь к базе данных'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='kauz_password',
            field=models.CharField(default='-', max_length=255, verbose_name='КАУЗ: Пароль'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='kauz_port',
            field=models.PositiveIntegerField(default='3050', verbose_name='КАУЗ: Порт'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='kauz_server_ip',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='КАУЗ: IP сервера'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='kauz_user',
            field=models.CharField(default='-', max_length=255, verbose_name='КАУЗ: Пользователь'),
        ),
    ]
