# Generated by Django 5.1 on 2024-11-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mainsettings_kauz_database_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='api_panel_patients_url',
            field=models.URLField(default='', max_length=500, verbose_name='URL для обновления панели пациентов'),
        ),
    ]
