# Generated by Django 5.1 on 2024-11-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_mainsettings_api_panel_patients_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsettings',
            name='api_panel_patients_url',
            field=models.URLField(default='http://10.37.170.101:8000/peopledash/api/registered_patients/', max_length=500, verbose_name='URL для обновления панели пациентов'),
        ),
    ]
