# Generated by Django 5.1 on 2024-12-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_mainsettings_api_panel_patients_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='api_update_registry_not_hospitalize_url',
            field=models.URLField(default='http://10.37.170.101:8000/api/patient_registry/', max_length=500, verbose_name='URL для обновления реестра не госпитализированных пациентов'),
        ),
    ]
