# Generated by Django 5.1 on 2025-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_mainsettings_api_update_registry_not_hospitalize_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='dagster_ip',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='Dagster IP'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='dagster_port',
            field=models.PositiveIntegerField(default=3000, verbose_name='Dagster Port'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='dash_chief_port',
            field=models.PositiveIntegerField(default=5010),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='dash_port',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='kauz_port',
            field=models.PositiveIntegerField(default=3050, verbose_name='КАУЗ: Порт'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='main_app_port',
            field=models.PositiveIntegerField(default=8000),
        ),
    ]
