# Generated by Django 5.1 on 2025-03-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_mainsettings_dagster_ip_mainsettings_dagster_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='filebrowser_ip',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='FileBrowser IP'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='filebrowser_port',
            field=models.PositiveIntegerField(default=8080, verbose_name='FileBrowser Port'),
        ),
    ]
