# Generated by Django 5.1 on 2025-03-28 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_mainsettings_filebrowser_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название бота')),
                ('bot_id', models.CharField(max_length=100, unique=True, verbose_name='ID бота')),
                ('token', models.CharField(max_length=255, verbose_name='Токен/Пароль бота')),
                ('additional_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительный пароль')),
            ],
            options={
                'verbose_name': 'Телеграм бот',
                'verbose_name_plural': 'Телеграм боты',
            },
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100, unique=True, verbose_name='ID группы')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание группы')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='home.telegrambot', verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Телеграм группа',
                'verbose_name_plural': 'Телеграм группы',
            },
        ),
    ]
