# Generated by Django 5.1 on 2025-03-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_telegrambot_telegramgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='alias',
            field=models.CharField(default=1, help_text='Уникальный идентификатор бота', max_length=50, unique=True, verbose_name='Псевдоним'),
            preserve_default=False,
        ),
    ]
