# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_telegrambot_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('link', models.CharField(blank=True, help_text='Имя URL (например: home, beneficiaries:home), путь (/admin/) или спец. код: dash_url, dash_chief_url, dash_update', max_length=255, verbose_name='Ссылка')),
                ('icon_type', models.CharField(choices=[('feather', 'Feather (data-feather)'), ('fa', 'Font Awesome (класс)')], default='feather', max_length=10, verbose_name='Тип иконки')),
                ('icon_name', models.CharField(blank=True, help_text='Например: home, bar-chart-2 или fa-heart-pulse', max_length=50, verbose_name='Иконка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
                ('slug', models.SlugField(blank=True, help_text='Латиница без пробелов, например: patient-registries (для пунктов с подменю)', max_length=50, null=True, unique=True, verbose_name='Идентификатор (для выпадающего блока)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.menuitem', verbose_name='Родитель (для подменю)')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
