# Generated by Django 5.1 on 2025-03-06 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_responsible', models.BooleanField(default=False, verbose_name='Ответственный')),
                ('is_executor', models.BooleanField(default=False, verbose_name='Исполнитель')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='journal.person', verbose_name='Персона')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('не распределено', 'Не распределено'), ('в работе', 'В работе'), ('сегодня срок ответа', 'Сегодня срок ответа'), ('просрочено', 'Просрочено'), ('отработано', 'Отработано')], default='не распределено', editable=False, max_length=20, verbose_name='Статус')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('response_deadline', models.DateField(blank=True, null=True, verbose_name='Дата срока ответа')),
                ('answer_date', models.DateField(blank=True, null=True, verbose_name='Дата ответа')),
                ('outgoing_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер исходящего письма')),
                ('related_appeals', models.ManyToManyField(blank=True, to='journal.appeal', verbose_name='Связанные обращения')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.article', verbose_name='Статья')),
                ('categories', models.ManyToManyField(blank=True, to='journal.category', verbose_name='Категория')),
                ('corpus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.corpus', verbose_name='Корпус')),
                ('executors', models.ManyToManyField(blank=True, related_name='appeals_as_executor', to='journal.employee', verbose_name='Исполнители')),
                ('responsible', models.ManyToManyField(blank=True, related_name='appeals_as_responsible', to='journal.employee', verbose_name='Ответственные')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals_as_applicant', to='journal.person', verbose_name='Заявитель')),
                ('patients', models.ManyToManyField(blank=True, related_name='appeals_as_patient', to='journal.person', verbose_name='Пациенты')),
                ('sources', models.ManyToManyField(blank=True, to='journal.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
    ]
