# Generated by Django 5.1 on 2025-03-10 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания работы'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
    ]
