# Generated by Django 5.1 on 2025-03-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_employee_end_date_employee_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
            ],
            options={
                'verbose_name': 'Код вопроса',
                'verbose_name_plural': 'Коды вопросов',
            },
        ),
    ]
