# Generated by Django 5.1 on 2025-03-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_citizenappeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenappeal',
            name='article_eight_closed',
            field=models.DateField(blank=True, null=True, verbose_name='Статья 8: закрыто (дата)'),
        ),
        migrations.AlterField(
            model_name='citizenappeal',
            name='article_eight_until',
            field=models.DateField(blank=True, null=True, verbose_name='Статья 8: находится в работе (до)'),
        ),
        migrations.AlterField(
            model_name='citizenappeal',
            name='article_ten_closed',
            field=models.DateField(blank=True, null=True, verbose_name='Статья 10: закрыто (дата)'),
        ),
        migrations.AlterField(
            model_name='citizenappeal',
            name='article_ten_until',
            field=models.DateField(blank=True, null=True, verbose_name='Статья 10: находится в работе (до)'),
        ),
        migrations.AlterField(
            model_name='citizenappeal',
            name='received_institution_closed',
            field=models.DateField(blank=True, null=True, verbose_name='Поступившее в учреждение: закрыто (дата)'),
        ),
        migrations.AlterField(
            model_name='citizenappeal',
            name='received_institution_until',
            field=models.DateField(blank=True, null=True, verbose_name='Поступившее в учреждение: находится в работе (до)'),
        ),
    ]
