# Generated by Django 5.1 on 2025-03-10 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_citizenappeal_article_eight_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenappeal',
            name='selected_responsible',
            field=models.ForeignKey(blank=True, help_text='Выберите одного сотрудника из списка ответственных и исполнителей обращения', null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.employee', verbose_name='Должность ответственного'),
        ),
    ]
