# Generated by Django 5.1 on 2025-03-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_citizenappeal_selected_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenappeal',
            name='selected_responsible',
            field=models.CharField(blank=True, help_text='Выберите должность из списка, сформированного по сотрудникам обращения', max_length=255, null=True, verbose_name='Должность ответственного'),
        ),
    ]
