# Generated by Django 5.1 on 2025-03-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_alter_citizenappeal_selected_responsible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Журнал обращений'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Справочник: статьи'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Справочник: категории'},
        ),
        migrations.AlterModelOptions(
            name='citizenappeal',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Журнал письменных обращений'},
        ),
        migrations.AlterModelOptions(
            name='corpus',
            options={'verbose_name': 'Корпус', 'verbose_name_plural': 'Справочник: корпуса'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Справочник: сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Персона', 'verbose_name_plural': 'Справочник: физические лица'},
        ),
        migrations.AlterModelOptions(
            name='questioncode',
            options={'verbose_name': 'Код вопроса', 'verbose_name_plural': 'Справочник: коды вопросов'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Источник', 'verbose_name_plural': 'Справочник: источники'},
        ),
        migrations.AlterField(
            model_name='citizenappeal',
            name='number_pp',
            field=models.IntegerField(help_text='Порядковый номер в журнале', unique_for_year='registration_date', verbose_name='№ п/п'),
        ),
    ]
