# Generated by Django 5.1 on 2025-03-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_alter_appeal_options_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('не распределено', 'Не распределено'), ('в работе', 'В работе'), ('сегодня срок ответа', 'Сегодня срок ответа'), ('просрочено', 'Просрочено'), ('отработано', 'Отработано'), ('отработано с просрочкой', 'Отработано с просрочкой')], default='не распределено', editable=False, max_length=30, verbose_name='Статус'),
        ),
    ]
