from django.db import models


class OMSData(models.Model):
    talon = models.CharField(max_length=255, unique=True)  # "Талон"
    source = models.CharField(max_length=255)  # "Источник"
    source_id = models.CharField(max_length=255)  # "ID источника"
    account_number = models.CharField(max_length=255)  # "Номер счёта"
    upload_date = models.CharField(max_length=255)  # "Дата выгрузки"
    cancellation_reason = models.CharField(max_length=255, null=True, blank=True)  # "Причина аннулирования"
    status = models.CharField(max_length=255)  # "Статус"
    talon_type = models.CharField(max_length=255)  # "Тип талона"
    goal = models.CharField(max_length=255, null=True, blank=True)  # "Цель"
    federal_goal = models.CharField(max_length=255, null=True, blank=True)  # "Фед. цель"
    patient = models.CharField(max_length=255)  # "Пациент"
    birth_date = models.CharField(max_length=255)  # "Дата рождения"
    age = models.CharField(max_length=255)  # "Возраст"
    gender = models.CharField(max_length=50)  # "Пол"
    policy = models.CharField(max_length=255)  # "Полис"
    smo_code = models.CharField(max_length=255)  # "Код СМО"
    insurance = models.CharField(max_length=255)  # "Страховая"
    enp = models.CharField(max_length=255)  # "ЕНП"
    treatment_start = models.CharField(max_length=255) # "Начало лечения"
    treatment_end = models.CharField(max_length=255) # "Окончание лечения"
    doctor = models.CharField(max_length=255)  # "Врач"
    doctor_profile = models.CharField(max_length=255)  # "Врач (Профиль МП)"
    staff_position = models.CharField(max_length=255)  # "Должность мед.персонала (V021)"
    department = models.CharField(max_length=255)  # "Подразделение"
    care_conditions = models.CharField(max_length=255)  # "Условия оказания помощи"
    medical_assistance_type = models.CharField(max_length=255)  # "Вид мед. помощи"
    disease_type = models.CharField(max_length=255)  # "Тип заболевания"
    main_disease_character = models.CharField(max_length=255)  # "Характер основного заболевания"
    visits = models.CharField(max_length=255)  # "Посещения"
    mo_visits = models.CharField(max_length=255) # "Посещения в МО"
    home_visits = models.CharField(max_length=255)  # "Посещения на Дому"
    case = models.CharField(max_length=255)  # "Случай"
    main_diagnosis = models.CharField(max_length=255)  # "Диагноз основной (DS1)"
    additional_diagnosis = models.CharField(max_length=255, null=True, blank=True)  # "Сопутствующий диагноз (DS2)"
    mp_profile = models.CharField(max_length=255)  # "Профиль МП"
    bed_profile = models.CharField(max_length=255)  # "Профиль койки"
    dispensary_monitoring = models.CharField(max_length=255)  # "Диспансерное наблюдение"
    specialty = models.CharField(max_length=255)  # "Специальность"
    outcome = models.CharField(max_length=255)  # "Исход"
    result = models.CharField(max_length=255)  # "Результат"
    operator = models.CharField(max_length=255)  # "Оператор"
    initial_input_date = models.CharField(max_length=255)  # "Первоначальная дата ввода"
    last_change_date = models.CharField(max_length=255)  # "Дата последнего изменения"
    tariff = models.CharField(max_length=255)  # "Тариф"
    amount = models.CharField(max_length=255)  # "Сумма"
    paid = models.CharField(max_length=255)  # "Оплачено"
    payment_type = models.CharField(max_length=255)  # "Тип оплаты"
    sanctions = models.CharField(max_length=255, null=True, blank=True)  # "Санкции"
    ksg = models.CharField(max_length=255, null=True, blank=True)  # "КСГ"
    kz = models.CharField(max_length=255, null=True, blank=True)  # "КЗ"
    therapy_schema_code = models.CharField(max_length=255, null=True, blank=True)  # "Код схемы лекарственной терапии"
    uet = models.CharField(max_length=255,null=True, blank=True)  # "УЕТ"
    classification_criterion = models.CharField(max_length=255, null=True, blank=True)  # "Классификационный критерий"
    shrm = models.CharField(max_length=255, null=True, blank=True)  # "ШРМ"
    directing_mo = models.CharField(max_length=255, null=True, blank=True)  # "МО, направившая"
    payment_method_code = models.CharField(max_length=255, null=True, blank=True)  # "Код способа оплаты"
    newborn = models.CharField(max_length=255, null=True, blank=True)  # "Новорожденный"
    representative = models.CharField(max_length=255, null=True, blank=True)  # "Представитель"
    additional_status_info = models.CharField(max_length=255, null=True, blank=True)  # "Доп. инф. о статусе талона"
    kslp = models.CharField(max_length=255, null=True, blank=True)  # "КСЛП"
    payment_source = models.CharField(max_length=255, null=True, blank=True)  # "Источник оплаты"
    report_period = models.CharField(max_length=255)  # "Отчетный период выгрузки"

    def __str__(self):
        return f"{self.talon} - {self.patient}"


class OMSDataImport(models.Model):
    csv_file = models.FileField(upload_to='uploads/')
    date_added = models.DateTimeField(auto_now_add=True)
    added_count = models.IntegerField(default=0)  # Количество добавленных записей
    updated_count = models.IntegerField(default=0)  # Количество обновленных записей
    error_count = models.IntegerField(default=0)  # Количество ошибок
