# Generated by Django 5.1 on 2024-10-07 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralOMSTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код цели')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование цели')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала действия')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания действия')),
            ],
            options={
                'verbose_name': 'Общая цель ОМС',
                'verbose_name_plural': 'Общие цели ОМС',
            },
        ),
        migrations.CreateModel(
            name='OMSTargetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория целей',
                'verbose_name_plural': 'Категории целей',
            },
        ),
        migrations.CreateModel(
            name='SQLQueryParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название параметра')),
                ('query', models.TextField(verbose_name='SQL-запрос')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='Параметры запроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'SQL Параметр',
                'verbose_name_plural': 'SQL Параметры',
            },
        ),
        migrations.CreateModel(
            name='MedicalOrganizationOMSTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная цель')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('general_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oms_reference.generalomstarget', verbose_name='Базовая цель')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.medicalorganization', verbose_name='Медицинская организация')),
                ('categories', models.ManyToManyField(blank=True, related_name='medical_targets', to='oms_reference.omstargetcategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Цель ОМС Медицинской организации',
                'verbose_name_plural': 'Цели ОМС Медицинских организаций',
                'unique_together': {('organization', 'general_target')},
            },
        ),
    ]
