# Generated by Django 5.1 on 2024-10-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusWebOMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус Web-ОМС',
                'verbose_name_plural': 'Статусы Web-ОМС',
            },
        ),
    ]
