# Generated by Django 5.1 on 2024-11-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_reference', '0002_statusweboms'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthGroup',
            fields=[
                ('iddr', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID группы')),
                ('drname', models.CharField(max_length=255, verbose_name='Название группы')),
                ('datebeg', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('dateend', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Группа здоровья',
                'verbose_name_plural': 'Группы здоровья',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id_source', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID источника')),
                ('source_name', models.CharField(max_length=255, verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Источник данных',
                'verbose_name_plural': 'Источники данных',
            },
        ),
    ]
