# Generated by Django 5.1 on 2024-11-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_reference', '0003_healthgroup_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id_goal', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID цели')),
                ('goal', models.CharField(max_length=200, verbose_name='Цель')),
                ('goal_name', models.TextField(verbose_name='Название цели')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
    ]
