# Generated by Django 5.1 on 2025-04-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_reference', '0004_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensaryDiagnoses168n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds', models.CharField(max_length=6, verbose_name='Диагноз')),
                ('profile', models.CharField(max_length=5, verbose_name='Профиль')),
                ('speciality', models.CharField(max_length=1000, verbose_name='Специальность')),
                ('speciality_join', models.CharField(max_length=1000, verbose_name='Совместная специальность')),
                ('group', models.CharField(max_length=100, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Диагноз по 168н',
                'verbose_name_plural': 'Диагнозы по 168н',
            },
        ),
    ]
