# Generated by Django 5.1 on 2025-03-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SickLeaveSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('eln', models.CharField(max_length=255, verbose_name='ЭЛН')),
                ('duplicate', models.CharField(max_length=255, verbose_name='Дубликат')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
                ('fss_status', models.CharField(max_length=255, verbose_name='Статус ФСС')),
                ('issue_date', models.CharField(max_length=255, verbose_name='Дата выдачи')),
                ('primary', models.CharField(max_length=255, verbose_name='Первичный')),
                ('previous_ln', models.CharField(max_length=255, verbose_name='Предыдущий ЛН')),
                ('next_ln', models.CharField(max_length=255, verbose_name='Следущий ЛН')),
                ('patient_last_name', models.CharField(max_length=255, verbose_name='Фамилия пациента')),
                ('patient_first_name', models.CharField(max_length=255, verbose_name='Имя пациента')),
                ('patient_middle_name', models.CharField(max_length=255, verbose_name='Отчество пациента')),
                ('birth_date', models.CharField(max_length=255, verbose_name='Дата рождения')),
                ('gender', models.CharField(max_length=255, verbose_name='Пол')),
                ('snils', models.CharField(max_length=255, verbose_name='СНИЛС')),
                ('age', models.CharField(max_length=255, verbose_name='Возраст')),
                ('workplace', models.CharField(max_length=255, verbose_name='Место работы')),
                ('incapacity_reason_code', models.CharField(max_length=255, verbose_name='Код причины нетрудоспособности')),
                ('mkb', models.CharField(max_length=255, verbose_name='МКБ')),
                ('incapacity_start_date', models.CharField(max_length=255, verbose_name='Период нетрудоспособности: дата начала')),
                ('incapacity_end_date', models.CharField(max_length=255, verbose_name='Период нетрудоспособности: дата окончания')),
                ('days_count', models.CharField(max_length=255, verbose_name='Количество дней')),
                ('tvsp', models.CharField(max_length=255, verbose_name='ТВСП')),
                ('issuing_doctor', models.CharField(max_length=255, verbose_name='Выдавший врач')),
                ('closing_doctor', models.CharField(max_length=255, verbose_name='Закрывший врач')),
                ('closing_date', models.CharField(max_length=255, verbose_name='Дата закрытия')),
                ('history_number', models.CharField(max_length=255, verbose_name='№ истории болезни')),
                ('patient_care', models.CharField(max_length=255, verbose_name='Уход за больными')),
            ],
            options={
                'verbose_name': 'Лист нетрудоспособности',
                'verbose_name_plural': 'Листы нетрудоспособности',
                'db_table': 'load_data_sick_leave_sheets',
            },
        ),
    ]
