# Generated by Django 5.1 on 2025-03-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0002_sickleavesheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sickleavesheet',
            old_name='primary',
            new_name='first',
        ),
    ]
