# Generated by Django 5.1 on 2025-03-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0003_rename_primary_sickleavesheet_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sickleavesheet',
            name='number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Номер'),
        ),
    ]
