# Generated by Django 5.1 on 2025-03-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0006_alter_complextalon_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispanseryISZL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('pid', models.CharField(max_length=50, unique=True, verbose_name='pID')),
                ('ldwid', models.CharField(max_length=50, verbose_name='ldwID')),
                ('pdwid', models.CharField(max_length=50, verbose_name='pdwID')),
                ('fio', models.CharField(max_length=255, verbose_name='FIO')),
                ('dr', models.CharField(max_length=50, verbose_name='DR')),
                ('ds', models.CharField(max_length=50, verbose_name='DS')),
                ('date_begin', models.CharField(default='-', max_length=50, verbose_name='DateBegin')),
                ('date_end', models.CharField(default='-', max_length=50, verbose_name='DateEnd')),
                ('id_reason', models.CharField(default='-', max_length=50, verbose_name='idReason')),
                ('name_reason', models.CharField(default='-', max_length=255, verbose_name='nameReason')),
                ('plan_month', models.CharField(default='-', max_length=10, verbose_name='PlanMonth')),
                ('plan_year', models.CharField(default='-', max_length=10, verbose_name='PlanYear')),
                ('fam_d', models.CharField(default='-', max_length=100, verbose_name='FAM_D')),
                ('im_d', models.CharField(default='-', max_length=100, verbose_name='IM_D')),
                ('ot_d', models.CharField(default='-', max_length=100, verbose_name='OT_D')),
                ('ss_d', models.CharField(default='-', max_length=50, verbose_name='SS_D')),
                ('spec_d', models.CharField(default='-', max_length=255, verbose_name='SPEC_D')),
                ('spec_v015', models.CharField(default='-', max_length=50, verbose_name='SpecV015')),
                ('date_info', models.CharField(default='-', max_length=50, verbose_name='DateInfo')),
                ('way_info', models.CharField(default='-', max_length=255, verbose_name='WayInfo')),
                ('res_info', models.CharField(default='-', max_length=255, verbose_name='ResInfo')),
                ('fact_dn', models.CharField(default='-', max_length=255, verbose_name='FactDN')),
                ('rezult_dn', models.CharField(default='-', max_length=255, verbose_name='RezultDN')),
                ('adr', models.CharField(default='-', max_length=255, verbose_name='ADR')),
                ('enp', models.CharField(default='-', max_length=255, verbose_name='ENP')),
                ('lpu', models.CharField(default='-', max_length=255, verbose_name='LPU')),
                ('fio_doctor', models.CharField(default='-', max_length=255, verbose_name='FIO_DOCTOR')),
                ('ss_doctor', models.CharField(default='-', max_length=50, verbose_name='SS_DOCTOR')),
                ('lpuuch', models.CharField(default='-', max_length=255, verbose_name='LPUUCH')),
                ('smo', models.CharField(default='-', max_length=50, verbose_name='SMO')),
                ('lpuauto', models.CharField(default='-', max_length=50, verbose_name='LPUAUTO')),
                ('lpudt', models.CharField(default='-', max_length=50, verbose_name='LPUDT')),
                ('user_update_list', models.CharField(default='-', max_length=50, verbose_name='UserUpdateList')),
                ('date_update_list', models.CharField(default='-', max_length=50, verbose_name='DateUpdateList')),
                ('user_update_plan', models.CharField(default='-', max_length=50, verbose_name='UserUpdatePlan')),
                ('date_update_plan', models.CharField(default='-', max_length=50, verbose_name='DateUpdatePlan')),
                ('period_w', models.CharField(default='-', max_length=50, verbose_name='PeriodW')),
                ('date_prev', models.CharField(default='-', max_length=50, verbose_name='DatePrev')),
                ('place_w', models.CharField(default='-', max_length=50, verbose_name='PlaceW')),
                ('w', models.CharField(default='-', max_length=50, verbose_name='w')),
                ('unemp', models.CharField(default='-', max_length=50, verbose_name='UNEMP')),
            ],
            options={
                'verbose_name': 'Диспансерное ИСЗЛ',
                'verbose_name_plural': 'Диспансерное ИСЗЛ',
                'db_table': 'load_data_dispansery_iszl',
            },
        ),
        migrations.CreateModel(
            name='PopulationISZL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('pid', models.CharField(max_length=50, unique=True, verbose_name='PID')),
                ('fio', models.CharField(max_length=255, verbose_name='FIO')),
                ('dr', models.CharField(max_length=50, verbose_name='DR')),
                ('smo', models.CharField(default='-', max_length=255, verbose_name='SMO')),
                ('enp', models.CharField(max_length=255, unique=True, verbose_name='ENP')),
                ('lpu', models.CharField(default='-', max_length=255, verbose_name='LPU')),
                ('ss_doctor', models.CharField(default='-', max_length=255, verbose_name='SS_DOCTOR')),
                ('lpuuch', models.CharField(default='-', max_length=255, verbose_name='LPUUCH')),
                ('upd', models.CharField(default='-', max_length=255, verbose_name='Upd')),
                ('closed', models.CharField(default='-', max_length=50, verbose_name='CLOSED')),
            ],
            options={
                'verbose_name': 'Население ИСЗЛ',
                'verbose_name_plural': 'Население ИСЗЛ',
                'db_table': 'load_data_iszl_population',
            },
        ),
    ]
