# Generated by Django 5.1 on 2025-03-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0007_dispanseryiszl_populationiszl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicMedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('epmd_id', models.CharField(max_length=255, unique=True, verbose_name='ИД')),
                ('original_epmz_id', models.CharField(default='-', max_length=255, verbose_name='ИД исходного ЭПМЗ')),
                ('document_date', models.CharField(default='-', max_length=255, verbose_name='Дата документа')),
                ('document_type', models.CharField(default='-', max_length=255, verbose_name='Тип документа')),
                ('doctor', models.CharField(default='-', max_length=255, verbose_name='Врач')),
                ('branch', models.CharField(default='-', max_length=255, verbose_name='Обособленное подразделение')),
                ('subdivision', models.CharField(default='-', max_length=255, verbose_name='Подразделение')),
                ('patient', models.CharField(default='-', max_length=255, verbose_name='Пациент')),
                ('formation_date', models.CharField(default='-', max_length=255, verbose_name='Дата формирования электронного документа')),
                ('doctor_signature', models.CharField(default='-', max_length=50, verbose_name='Наличие подписи врача')),
                ('organization_signature', models.CharField(default='-', max_length=50, verbose_name='Наличие подписи МО')),
                ('sending_date', models.CharField(default='-', max_length=255, verbose_name='Дата отправки в РИР.РЭМД')),
                ('sending_status', models.CharField(default='-', max_length=255, verbose_name='Статус отправки в РИР.РЭМД')),
                ('registration_number', models.CharField(default='-', max_length=255, verbose_name='Регистрационный номер')),
                ('status_details', models.TextField(default='-', verbose_name='Детали статуса отправки')),
            ],
            options={
                'verbose_name': 'Электронный медицинский документ',
                'verbose_name_plural': 'Электронные медицинские документы',
                'db_table': 'load_data_emd',
            },
        ),
    ]
