# Generated by Django 5.1 on 2025-03-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0008_electronicmedicaldocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='Номер')),
                ('series', models.CharField(default='-', max_length=255, verbose_name='Серия')),
                ('recipe_type', models.CharField(default='-', max_length=255, verbose_name='Тип рецепта')),
                ('date', models.CharField(default='-', max_length=255, verbose_name='Дата')),
                ('digital_signature', models.CharField(default='-', max_length=255, verbose_name='ЭЦП')),
                ('signature_owner', models.CharField(default='-', max_length=255, verbose_name='Владелец подписи')),
                ('organization', models.CharField(default='-', max_length=255, verbose_name='Организация')),
                ('subdivision', models.CharField(default='-', max_length=255, verbose_name='Подразделение')),
                ('sending_status_rir_farm', models.CharField(default='-', max_length=255, verbose_name='Статус отправки РИР/ФАРМ')),
                ('additional_status_info_rir', models.TextField(default='-', verbose_name='Дополнительная информация по статусу отправки в РИР')),
                ('status', models.CharField(default='-', max_length=255, verbose_name='Статус')),
                ('status_change_date', models.CharField(default='-', max_length=255, verbose_name='Дата изменения статуса')),
                ('status_author', models.CharField(default='-', max_length=255, verbose_name='Автор статуса')),
                ('first_er_status', models.CharField(default='-', max_length=255, verbose_name='1ЭР (статус отправки)')),
                ('emd_verification', models.CharField(default='-', max_length=255, verbose_name='Верификация ЭМД')),
                ('sending_status_remd', models.CharField(default='-', max_length=255, verbose_name='Статус отправки в РЭМД')),
                ('additional_status_info_remd', models.TextField(default='-', verbose_name='Дополнительная информация по статусу отправки в РЭМД')),
                ('validity_period', models.CharField(default='-', max_length=255, verbose_name='Срок действия')),
                ('patient_full_name', models.CharField(default='-', max_length=255, verbose_name='Ф.И.О. пациента')),
                ('patient_birth_date', models.CharField(default='-', max_length=255, verbose_name='Дата рождения пациента')),
                ('patient_snils', models.CharField(default='-', max_length=255, verbose_name='СНИЛС пациента')),
                ('diagnosis_code', models.CharField(default='-', max_length=255, verbose_name='Код диагноза')),
                ('diagnosis_name', models.CharField(default='-', max_length=255, verbose_name='Название диагноза')),
                ('benefit_category_name', models.CharField(default='-', max_length=255, verbose_name='Название льготной категории')),
                ('benefit_category_type', models.CharField(default='-', max_length=255, verbose_name='Тип льготной категории')),
                ('financing_source', models.CharField(default='-', max_length=255, verbose_name='Источник финансирования')),
                ('doctor_full_name', models.CharField(default='-', max_length=255, verbose_name='Ф.И.О. врача')),
                ('doctor_position', models.CharField(default='-', max_length=255, verbose_name='Должность врача')),
                ('medicinal_product', models.CharField(default='-', max_length=255, verbose_name='Лекарственный препарат')),
                ('trn', models.CharField(default='-', max_length=255, verbose_name='ТРН')),
                ('inn', models.CharField(default='-', max_length=255, verbose_name='МНН')),
                ('quantity_total_prescribed', models.CharField(default='-', max_length=255, verbose_name='Кол-во/Всего назначено')),
                ('payment_percentage', models.CharField(default='-', max_length=255, verbose_name='Процент оплаты')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'db_table': 'load_data_recipes',
            },
        ),
    ]
