# Generated by Django 5.1 on 2025-03-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0009_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='inn',
            field=models.TextField(default='-', verbose_name='МНН'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='medicinal_product',
            field=models.TextField(default='-', verbose_name='Лекарственный препарат'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='trn',
            field=models.TextField(default='-', verbose_name='ТРН'),
        ),
    ]
