# Generated by Django 5.1 on 2025-03-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0011_mortalityrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortalityrecord',
            name='additional_initial_statistic',
        ),
        migrations.RemoveField(
            model_name='mortalityrecord',
            name='additional_issue_date',
        ),
        migrations.RemoveField(
            model_name='mortalityrecord',
            name='additional_number',
        ),
        migrations.RemoveField(
            model_name='mortalityrecord',
            name='recipe_type',
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='mortality_type',
            field=models.CharField(default='-', max_length=255, verbose_name='Тип'),
        ),
    ]
