# Generated by Django 5.1 on 2025-03-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0012_remove_mortalityrecord_additional_initial_statistic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('series_number', models.CharField(max_length=255, unique=True, verbose_name='Серия и номер справки')),
                ('issue_date', models.CharField(default='-', max_length=255, verbose_name='Дата выдачи')),
                ('full_name', models.CharField(default='-', max_length=255, verbose_name='ФИО')),
                ('birth_date', models.CharField(default='-', max_length=255, verbose_name='Дата рождения')),
                ('doctor', models.CharField(default='-', max_length=255, verbose_name='Врач')),
                ('organization', models.CharField(default='-', max_length=255, verbose_name='Организация выдавшая документ')),
                ('reference_type', models.CharField(default='-', max_length=255, verbose_name='Вид справки')),
                ('conclusion', models.CharField(default='-', max_length=255, verbose_name='Заключение')),
                ('status', models.CharField(default='-', max_length=255, verbose_name='Статус')),
                ('errors', models.TextField(default='-', verbose_name='Ошибки по справке')),
            ],
            options={
                'verbose_name': 'Справка',
                'verbose_name_plural': 'Справки',
                'db_table': 'load_data_reference',
            },
        ),
    ]
