# Generated by Django 5.1 on 2025-03-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0013_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='talon',
            name='report_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talon',
            name='report_year',
            field=models.CharField(default='-', max_length=4),
        ),
    ]
