# Generated by Django 5.1 on 2025-03-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0014_talon_report_month_talon_report_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextalon',
            name='report_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complextalon',
            name='report_year',
            field=models.CharField(default='-', max_length=4),
        ),
    ]
