# Generated by Django 5.1 on 2025-03-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0015_complextalon_report_month_complextalon_report_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, verbose_name='Таблица')),
                ('start_time', models.DateTimeField(verbose_name='Время старта')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('count_before', models.IntegerField(verbose_name='Количество до обновления')),
                ('count_after', models.IntegerField(verbose_name='Количество после обновления')),
                ('duration', models.FloatField(help_text='Длительность в секундах', verbose_name='Длительность')),
                ('error_occurred', models.BooleanField(default=False, verbose_name='Ошибка')),
                ('error_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код ошибки')),
                ('run_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на запуск')),
            ],
            options={
                'verbose_name': 'Лог загрузки',
                'verbose_name_plural': 'Логи загрузок',
            },
        ),
    ]
