# Generated by Django 5.1 on 2025-03-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0016_loadlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispanseryiszl',
            name='pdwid',
            field=models.CharField(max_length=50, unique=True, verbose_name='pdwID'),
        ),
        migrations.AlterField(
            model_name='dispanseryiszl',
            name='pid',
            field=models.CharField(max_length=50, verbose_name='pID'),
        ),
    ]
