# Generated by Django 5.1 on 2025-04-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0017_alter_dispanseryiszl_pdwid_alter_dispanseryiszl_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('snils', models.CharField(max_length=255, unique=True, verbose_name='СНИЛС')),
                ('doctor_code', models.CharField(default='-', max_length=255, verbose_name='Код врача')),
                ('last_name', models.CharField(default='-', max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(default='-', max_length=255, verbose_name='Имя')),
                ('middle_name', models.CharField(default='-', max_length=255, verbose_name='Отчество')),
                ('birth_date', models.CharField(default='-', max_length=255, verbose_name='Дата рождения')),
                ('gender', models.CharField(default='-', max_length=255, verbose_name='Пол')),
                ('start_date', models.CharField(default='-', max_length=255, verbose_name='Дата начала работы')),
                ('end_date', models.CharField(default='-', max_length=255, verbose_name='Дата окончания работы')),
                ('department', models.CharField(default='-', max_length=255, verbose_name='Структурное подразделение')),
                ('medical_profile_code', models.CharField(default='-', max_length=255, verbose_name='Код профиля медпомощи')),
                ('specialty_code', models.CharField(default='-', max_length=255, verbose_name='Код специальности')),
                ('department_code', models.CharField(default='-', max_length=255, verbose_name='Код отделения')),
                ('comment', models.CharField(default='-', max_length=255, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
                'db_table': 'load_data_doctor',
                'constraints': [models.UniqueConstraint(fields=('snils', 'doctor_code'), name='unique_snils_code_doctor')],
            },
        ),
    ]
