# Generated by Django 5.1 on 2025-04-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0018_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='snils',
            field=models.CharField(max_length=255, verbose_name='СНИЛС'),
        ),
    ]
