# Generated by Django 5.1 on 2025-04-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0020_talonrefusal_detailedmedicalexamination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talonrefusal',
            name='tfoms_error_text',
            field=models.TextField(default='-', verbose_name='Текст ошибки ТФОМС'),
        ),
    ]
