# Generated by Django 5.1 on 2025-04-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0021_alter_talonrefusal_tfoms_error_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complextalon',
            name='additional_diagnosis',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='detailedmedicalexamination',
            name='additional_diagnosis',
            field=models.CharField(default='-', max_length=1000, verbose_name='Сопутствующий диагноз'),
        ),
        migrations.AlterField(
            model_name='talon',
            name='additional_diagnosis',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
    ]
