# Generated by Django 5.1 on 2025-04-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0022_alter_complextalon_additional_diagnosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAppeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_last_name', models.CharField(default='-', max_length=255, verbose_name='Фамилия пациента')),
                ('patient_first_name', models.CharField(default='-', max_length=255, verbose_name='Имя пациента')),
                ('patient_middle_name', models.CharField(default='-', max_length=255, verbose_name='Отчество пациента')),
                ('birth_date', models.CharField(default='-', max_length=50, verbose_name='Дата рождения')),
                ('gender', models.CharField(default='-', max_length=50, verbose_name='Пол')),
                ('phone', models.CharField(default='-', max_length=50, verbose_name='Телефон')),
                ('enp', models.CharField(default='-', max_length=255, verbose_name='ЕНП')),
                ('attachment', models.CharField(default='-', max_length=255, verbose_name='Прикрепление')),
                ('series', models.CharField(default='-', max_length=50, verbose_name='Серия')),
                ('number', models.CharField(default='-', max_length=50, verbose_name='Номер')),
                ('employee_last_name', models.CharField(default='-', max_length=255, verbose_name='Фамилия сотрудника')),
                ('employee_first_name', models.CharField(default='-', max_length=255, verbose_name='Имя сотрудника')),
                ('employee_middle_name', models.CharField(default='-', max_length=255, verbose_name='Отчество сотрудника')),
                ('position', models.CharField(default='-', max_length=255, verbose_name='Должность')),
                ('acceptance_date', models.CharField(default='-', max_length=50, verbose_name='Дата приема')),
                ('record_date', models.CharField(default='-', max_length=50, verbose_name='Дата записи')),
                ('schedule_type', models.CharField(default='-', max_length=255, verbose_name='Тип расписания')),
                ('record_source', models.CharField(default='-', max_length=255, verbose_name='Источник записи')),
                ('department', models.CharField(default='-', max_length=255, verbose_name='Подразделение')),
                ('creator', models.CharField(default='-', max_length=255, verbose_name='Создавший')),
                ('no_show', models.CharField(default='-', max_length=50, verbose_name='Не явился')),
                ('epmz', models.CharField(default='-', max_length=255, verbose_name='ЭПМЗ')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'db_table': 'load_data_journal_appeals',
                'unique_together': {('enp', 'employee_last_name', 'acceptance_date')},
            },
        ),
    ]
