# Generated by Django 5.1 on 2025-04-21 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0023_journalappeals'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextalon',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ИД источника'),
        ),
        migrations.AddField(
            model_name='electronicmedicaldocument',
            name='talon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emds', to='load_data.talon'),
        ),
        migrations.AddField(
            model_name='talon',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ИД источника'),
        ),
    ]
