# Generated by Django 5.1 on 2025-04-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0024_complextalon_source_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complextalon',
            name='place_service',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='talon',
            name='place_service',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
