# Generated by Django 5.1 on 2025-04-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0025_complextalon_place_service_talon_place_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispanseryWorkISZL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('external_id', models.CharField(max_length=50, unique=True, verbose_name='id')),
                ('mo_prof_m', models.CharField(default='-', max_length=255, verbose_name='МО проф.м.')),
                ('mo_prikreplenia', models.CharField(default='-', max_length=255, verbose_name='МО прикрепления')),
                ('org_prof_m', models.CharField(default='-', max_length=255, verbose_name='Организация Проф.м.')),
                ('address', models.CharField(default='-', max_length=255, verbose_name='Адрес')),
                ('fio', models.CharField(default='-', max_length=255, verbose_name='Ф.И.О.')),
                ('dr', models.CharField(default='-', max_length=50, verbose_name='Д.Р.')),
                ('enp', models.CharField(default='-', max_length=50, verbose_name='ЕНП')),
                ('ds', models.CharField(default='-', max_length=50, verbose_name='DS')),
                ('date', models.CharField(default='-', max_length=50, verbose_name='Дата')),
                ('time', models.CharField(default='-', max_length=50, verbose_name='Время')),
                ('inf', models.CharField(default='-', max_length=255, verbose_name='Инф.')),
                ('fact', models.CharField(default='-', max_length=255, verbose_name='Факт')),
                ('smo', models.CharField(default='-', max_length=50, verbose_name='СМО')),
                ('date_change_operator', models.CharField(default='-', max_length=255, verbose_name='Дата изм./Оператор')),
            ],
            options={
                'verbose_name': 'МО – профиль и прикрепление',
                'verbose_name_plural': 'МО – профиль и прикрепление',
                'db_table': 'load_data_dn_work_iszl',
            },
        ),
    ]
