# Generated by Django 5.1 on 2025-05-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0026_dispanseryworkiszl'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('talon', models.CharField(default='-', max_length=255, verbose_name='Талон')),
                ('month', models.CharField(default='-', max_length=20, verbose_name='Месяц')),
                ('report_month', models.IntegerField(default=0, verbose_name='Номер месяца')),
                ('report_year', models.IntegerField(default=0, verbose_name='Год отчёта')),
                ('source_id', models.CharField(db_index=True, default='-', max_length=255, verbose_name='ИД источника')),
                ('place_service', models.CharField(default='-', max_length=255, verbose_name='Место обслуживания')),
                ('status', models.CharField(default='-', max_length=255, verbose_name='Статус')),
                ('goal', models.CharField(default='-', max_length=255, verbose_name='Цель')),
                ('patient', models.CharField(default='-', max_length=255, verbose_name='Пациент')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('treatment_start', models.DateField(blank=True, null=True, verbose_name='Начало лечения')),
                ('treatment_end', models.DateField(blank=True, null=True, verbose_name='Окончание лечения')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('gender', models.CharField(default='-', max_length=50, verbose_name='Пол')),
                ('enp', models.CharField(default='-', max_length=255, verbose_name='ЕНП')),
                ('smo_code', models.CharField(default='-', max_length=255, verbose_name='Код СМО')),
                ('inogorodniy', models.BooleanField(default=False, verbose_name='Иногородний')),
                ('visits', models.IntegerField(default=0, verbose_name='Визиты')),
                ('mo_visits', models.IntegerField(default=0, verbose_name='Визиты в МО')),
                ('home_visits', models.IntegerField(default=0, verbose_name='Визиты на дому')),
                ('main_diagnosis_code', models.CharField(default='-', max_length=50, verbose_name='Код основного диагноза')),
                ('additional_diagnosis_codes', models.CharField(default='-', max_length=255, verbose_name='Коды доп. диагнозов')),
                ('initial_input_date', models.DateField(blank=True, null=True, verbose_name='Дата ввода')),
                ('last_change_date', models.DateField(blank=True, null=True, verbose_name='Дата изменения')),
                ('amount_numeric', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('sanctions', models.CharField(default='-', max_length=255, verbose_name='Санкции')),
                ('ksg', models.CharField(default='-', max_length=255, verbose_name='КСГ')),
                ('department_id', models.IntegerField(default=0, verbose_name='ID отделения')),
                ('department', models.CharField(default='-', max_length=255, verbose_name='Отделение')),
                ('building_id', models.IntegerField(default=0, verbose_name='ID корпуса')),
                ('building', models.CharField(default='-', max_length=255, verbose_name='Корпус')),
                ('doctor_code', models.CharField(default='-', max_length=255, verbose_name='Код врача')),
                ('doctor_id', models.IntegerField(default=0, verbose_name='ID врача')),
                ('doctor', models.CharField(default='-', max_length=255, verbose_name='Врач')),
                ('specialty', models.CharField(default='-', max_length=255, verbose_name='Специальность')),
                ('profile', models.CharField(default='-', max_length=255, verbose_name='Профиль')),
                ('profile_id', models.IntegerField(default=0, verbose_name='ID профиля')),
                ('health_group', models.CharField(default='-', max_length=255, verbose_name='Группа здоровья')),
                ('attached', models.BooleanField(default=True, verbose_name='Прикреплен')),
            ],
            options={
                'verbose_name': 'ОМС: Сводные данные',
                'verbose_name_plural': 'ОМС: Сводные данные',
                'db_table': 'load_data_oms_data',
                'indexes': [models.Index(fields=['source_id'], name='omsdata_source_id_idx'), models.Index(fields=['talon', 'source_id', 'doctor_code'], name='omsdata_talon_src_doc_idx')],
            },
        ),
    ]
