# Generated by Django 5.1 on 2025-05-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0027_omsdata'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='omsdata',
            name='omsdata_talon_src_doc_idx',
        ),
        migrations.AddIndex(
            model_name='omsdata',
            index=models.Index(fields=['doctor_code'], name='omsdata_doctor_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='omsdata',
            constraint=models.UniqueConstraint(fields=('talon', 'source_id', 'doctor_code'), name='omsdata_talon_src_doc_uniq'),
        ),
    ]
