# Generated by Django 5.1 on 2025-11-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0028_remove_omsdata_omsdata_talon_src_doc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvazarAnalysisOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='Номер')),
                ('status', models.CharField(default='-', max_length=255, verbose_name='Статус')),
                ('lis', models.CharField(default='-', max_length=255, verbose_name='ЛИС')),
                ('patient', models.CharField(default='-', max_length=255, verbose_name='Пациент')),
                ('doctor', models.CharField(default='-', max_length=255, verbose_name='Врач')),
                ('operator', models.CharField(default='-', max_length=255, verbose_name='Оператор')),
                ('diagnosis', models.CharField(default='-', max_length=255, verbose_name='Диагноз')),
                ('services', models.TextField(default='-', verbose_name='Услуги')),
                ('order_created_at', models.CharField(default='-', max_length=255, verbose_name='Создан')),
                ('payment_source', models.CharField(default='-', max_length=255, verbose_name='Источник оплаты')),
                ('emd_status', models.CharField(default='-', max_length=255, verbose_name='Статус ЭМД')),
                ('nns_vimis_status', models.CharField(default='-', max_length=255, verbose_name='Статус ННС ВИМИС')),
                ('rns_vimis_status', models.CharField(default='-', max_length=255, verbose_name='Статус (Р)НС ВИМИС')),
            ],
            options={
                'verbose_name': 'Квазар: заказ анализа',
                'verbose_name_plural': 'Квазар: заказы анализов',
                'db_table': 'load_data_kvazar_analysis_orders',
            },
        ),
    ]
