# Generated by Django 5.1 on 2025-11-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0029_kvazaranalysisorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvazaranalysisorder',
            name='diagnosis',
            field=models.CharField(default='-', max_length=500, verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='kvazaranalysisorder',
            name='doctor',
            field=models.CharField(default='-', max_length=500, verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='kvazaranalysisorder',
            name='operator',
            field=models.CharField(default='-', max_length=500, verbose_name='Оператор'),
        ),
    ]
