# Generated by Django 5.1 on 2026-08-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_data', '0035_alter_kvazaranalysisorder_long_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnKvazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('enp', models.CharField(db_index=True, default='-', max_length=64, verbose_name='ЕНП')),
                ('fio', models.CharField(default='-', max_length=255, verbose_name='ФИО')),
                ('dr', models.CharField(default='-', max_length=50, verbose_name='Дата рождения')),
                ('sex', models.CharField(default='-', max_length=20, verbose_name='Пол')),
                ('phone', models.CharField(default='-', max_length=64, verbose_name='Телефон')),
                ('ds', models.CharField(default='-', max_length=512, verbose_name='Диагноз (сырой)')),
                ('ds_code', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Код МКБ')),
                ('date_begin', models.CharField(default='-', max_length=50, verbose_name='Дата постановки')),
                ('date_end', models.CharField(default='-', max_length=50, verbose_name='Дата снятия')),
                ('doctor', models.CharField(default='-', max_length=255, verbose_name='Врач')),
                ('specialty', models.CharField(default='-', max_length=255, verbose_name='Специальность')),
                ('lpuuch', models.CharField(default='-', max_length=255, verbose_name='Участок')),
                ('mo', models.CharField(default='-', max_length=255, verbose_name='МО')),
                ('row_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Хеш строки')),
                ('source_file', models.CharField(default='-', max_length=255, verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'ДН Квазар',
                'verbose_name_plural': 'ДН Квазар',
                'db_table': 'load_data_dn_kvazar',
                'indexes': [models.Index(fields=['enp', 'ds_code'], name='load_data_d_enp_bb0794_idx')],
            },
        ),
    ]
