# Generated by Django 5.1 on 2025-03-11 21:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kadry', '0002_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус талона',
                'verbose_name_plural': 'Статусы талонов',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('report_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Отчетный месяц')),
                ('report_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)], verbose_name='Отчетный год')),
                ('treatment_start', models.DateField(verbose_name='Начало лечения')),
                ('treatment_end', models.DateField(verbose_name='Окончание лечения')),
                ('visits', models.PositiveIntegerField(verbose_name='Посещения')),
                ('visits_in_mo', models.PositiveIntegerField(verbose_name='Посещения в МО')),
                ('visits_at_home', models.PositiveIntegerField(verbose_name='Посещения на дому')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='Диагноз')),
                ('diagnosis_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Диагноз 2')),
                ('diagnosis_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Диагноз 3')),
                ('diagnosis_4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Диагноз 4')),
                ('health_group', models.CharField(blank=True, max_length=255, null=True, verbose_name='Группа здоровья')),
                ('ksg', models.CharField(blank=True, max_length=255, null=True, verbose_name='КСГ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('sanctions', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Санкции')),
                ('formation_date', models.DateField(verbose_name='Дата формирования')),
                ('change_date', models.DateField(verbose_name='Дата изменения')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено')),
                ('blocked', models.BooleanField(default=False, verbose_name='Заблокировано')),
                ('doctor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadry.doctorcode', verbose_name='Код врача')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talon.goal', verbose_name='Цель')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.physicalperson', verbose_name='Пациент')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talon.source', verbose_name='Источник')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talon.ticketstatus', verbose_name='Статус талона')),
            ],
            options={
                'verbose_name': 'Талон',
                'verbose_name_plural': 'Талоны',
                'indexes': [models.Index(fields=['number'], name='talon_ticke_number_1353a9_idx')],
            },
        ),
    ]
