# Generated by Django 5.1 on 2025-05-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talon', '0001_initial'),
    ]

    operations = [
    ]
