# Generated by Django 5.1 on 2024-12-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='№ п/п')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('medical_organization', models.CharField(max_length=255, verbose_name='Прикрепление к МО')),
                ('hospital_name', models.CharField(max_length=255, verbose_name='Наименование стационара')),
                ('admission_date', models.DateField(verbose_name='Дата обращения в приемное отделение')),
                ('referral_method', models.CharField(choices=[('SSMP', 'ССМП'), ('self_referral', 'Самообращение')], max_length=20, verbose_name='Способ обращения')),
                ('admission_diagnosis', models.CharField(max_length=255, verbose_name='Диагноз при поступлении')),
                ('refusal_date', models.DateField(blank=True, null=True, verbose_name='Дата отказа')),
                ('refusal_reason', models.CharField(choices=[('not_indication', 'Нет показаний для госпитализации'), ('patient_refusal', 'Отказ пациента (законного представителя)')], max_length=50, verbose_name='Причина отказа в госпитализации')),
            ],
            options={
                'verbose_name': 'Реестр не госпитализированных пациентов',
                'verbose_name_plural': 'Реестр не госпитализированных пациентов',
                'ordering': ['number'],
            },
        ),
    ]
