# Generated by Django 5.1 on 2024-12-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_patientregistry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistry',
            name='refusal_date',
            field=models.DateField(verbose_name='Дата отказа'),
        ),
    ]
