# Generated by Django 5.1 on 2024-10-31 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Группа')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень вложенности')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='plan.groupindicators')),
            ],
        ),
        migrations.CreateModel(
            name='FilterCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Поле фильтрации')),
                ('filter_type', models.CharField(choices=[('exact', 'Точное соответствие (=)'), ('in', 'В списке (IN)'), ('like', 'Похож на (LIKE)')], max_length=10, verbose_name='Тип фильтра')),
                ('values', models.TextField(verbose_name='Значения (через запятую)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='plan.groupindicators')),
            ],
        ),
        migrations.CreateModel(
            name='OptionsForReportFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год отчета')),
                ('purpose', models.CharField(max_length=50, verbose_name='Цель')),
                ('sum_values', models.TextField(blank=True, null=True, verbose_name='Сумма')),
                ('visits', models.IntegerField(blank=True, null=True, verbose_name='Посещения на дому')),
                ('profile_mp', models.CharField(blank=True, max_length=50, null=True, verbose_name='Профиль МП')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.groupindicators', verbose_name='Группа')),
            ],
        ),
    ]
