# Generated by Django 5.1 on 2024-10-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercondition',
            name='additional_condition_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дополнительное поле фильтрации'),
        ),
        migrations.AddField(
            model_name='filtercondition',
            name='additional_condition_type',
            field=models.CharField(blank=True, choices=[('exact', 'Точное соответствие (=)'), ('in', 'В списке (IN)'), ('like', 'Похож на (LIKE)')], max_length=10, null=True, verbose_name='Тип дополнительного фильтра'),
        ),
        migrations.AddField(
            model_name='filtercondition',
            name='additional_values',
            field=models.TextField(blank=True, null=True, verbose_name='Значения для дополнительного фильтра'),
        ),
    ]
