# Generated by Django 5.1 on 2024-10-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_filtercondition_additional_condition_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtercondition',
            name='additional_condition_field',
        ),
        migrations.RemoveField(
            model_name='filtercondition',
            name='additional_condition_type',
        ),
        migrations.RemoveField(
            model_name='filtercondition',
            name='additional_values',
        ),
    ]
