# Generated by Django 5.1 on 2024-10-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_remove_filtercondition_additional_condition_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercondition',
            name='year',
            field=models.IntegerField(default=2024, verbose_name='Год действия фильтра'),
        ),
    ]
