# Generated by Django 5.1 on 2024-11-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_remove_filtercondition_goals_monthlyplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtercondition',
            name='filter_type',
            field=models.CharField(choices=[('exact', 'Точное соответствие (=)'), ('in', 'В списке (IN)'), ('like', 'Похож на (LIKE)'), ('not_like', 'Не содержит (NOT LIKE)')], max_length=10, verbose_name='Тип фильтра'),
        ),
    ]
