# Generated by Django 5.1 on 2024-11-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_alter_filtercondition_filter_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('field_name', models.CharField(max_length=100, verbose_name='Поле для фильтрации')),
                ('filter_type', models.CharField(choices=[('exact', 'Точное соответствие (=)'), ('in', 'В списке (IN)'), ('like', 'Похож на (LIKE)'), ('not_like', 'Не содержит (NOT LIKE)')], max_length=10, verbose_name='Тип фильтра')),
                ('values', models.TextField(verbose_name='Значения (через запятую)')),
            ],
            options={
                'verbose_name': 'Общий фильтр',
                'verbose_name_plural': 'Общие фильтры',
            },
        ),
    ]
