# Generated by Django 5.1 on 2024-11-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_remove_unifiedfilter_field_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedfiltercondition',
            name='operator',
            field=models.CharField(choices=[('AND', 'И'), ('OR', 'ИЛИ')], default='AND', max_length=3, verbose_name='Оператор'),
        ),
    ]
