# Generated by Django 5.1 on 2024-11-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_unifiedfiltercondition_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedfiltercondition',
            name='filter_type',
            field=models.CharField(choices=[('exact', 'Точное соответствие (=)'), ('in', 'В списке (IN)'), ('like', 'Похож на (LIKE)'), ('not_like', 'Не содержит (NOT LIKE)'), ('<', 'Меньше (<)'), ('>', 'Больше (>)')], max_length=10, verbose_name='Тип фильтра'),
        ),
    ]
