# Generated by Django 5.1 on 2024-11-26 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_alter_unifiedfiltercondition_filter_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_plans', to='plan.groupindicators', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'План на год',
                'verbose_name_plural': 'Планы на год',
                'unique_together': {('group', 'year')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='monthlyplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monthlyplan',
            name='annual_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to='plan.annualplan', verbose_name='Годовой план'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyplan',
            unique_together={('annual_plan', 'month')},
        ),
        migrations.RemoveField(
            model_name='monthlyplan',
            name='group',
        ),
    ]
