# Generated by Django 5.1 on 2024-11-27 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_station_doctorassignment'),
        ('plan', '0012_annualplan_alter_monthlyplan_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filtercondition',
            options={'verbose_name': 'Условие фильтра', 'verbose_name_plural': 'Условия фильтра'},
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Деньги'),
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='annual_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to='plan.annualplan', verbose_name='Годовой план'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlyplan',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterUniqueTogether(
            name='filtercondition',
            unique_together={('group', 'field_name', 'filter_type', 'year')},
        ),
        migrations.CreateModel(
            name='BuildingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_plans', to='plan.annualplan', verbose_name='Годовой план')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_plans', to='organization.building', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'План корпуса',
                'verbose_name_plural': 'Планы корпусов',
                'unique_together': {('annual_plan', 'building')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_plans', to='plan.buildingplan', verbose_name='План корпуса')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_plans', to='organization.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'План отделения',
                'verbose_name_plural': 'Планы отделений',
                'unique_together': {('building_plan', 'department')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyBuildingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Бюджет')),
                ('building_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_building_plans', to='plan.buildingplan', verbose_name='План корпуса')),
            ],
            options={
                'verbose_name': 'Месячный план корпуса',
                'verbose_name_plural': 'Месячные планы корпусов',
                'unique_together': {('building_plan', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyDepartmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Бюджет')),
                ('department_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_department_plans', to='plan.departmentplan', verbose_name='План отделения')),
            ],
            options={
                'verbose_name': 'Месячный план отделения',
                'verbose_name_plural': 'Месячные планы отделений',
                'unique_together': {('department_plan', 'month')},
            },
        ),
    ]
