# Generated by Django 5.1 on 2024-11-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_station_doctorassignment'),
        ('plan', '0013_alter_filtercondition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupindicators',
            name='buildings',
            field=models.ManyToManyField(blank=True, help_text='Укажите корпуса, связанные с этой группой (для распределяемых планов)', to='organization.building', verbose_name='Корпуса'),
        ),
        migrations.AddField(
            model_name='groupindicators',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Выберите отделения, доступные для распределения планов', to='organization.department', verbose_name='Отделения'),
        ),
        migrations.AddField(
            model_name='groupindicators',
            name='is_distributable',
            field=models.BooleanField(default=False, help_text='Отметьте, если для этой группы требуется распределение по корпусам и отделениям', verbose_name='Распределяемый план'),
        ),
    ]
