# Generated by Django 5.1 on 2024-12-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_groupbuildingdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiefDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('goal', models.CharField(max_length=100, verbose_name='Цель')),
                ('year', models.IntegerField(default=2024, verbose_name='Год')),
                ('plan', models.IntegerField(default=0, verbose_name='План')),
                ('finance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Финансы')),
            ],
            options={
                'unique_together': {('name', 'goal', 'year')},
            },
        ),
    ]
