# Generated by Django 5.1 on 2024-12-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0016_chiefdashboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chiefdashboard',
            options={'verbose_name': 'Показатель', 'verbose_name_plural': 'Панель главного врача'},
        ),
    ]
