# Generated by Django 5.1 on 2025-01-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0017_alter_chiefdashboard_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiefdashboard',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='filtercondition',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Год действия фильтра'),
        ),
    ]
