# Generated by Django 5.1 on 2025-01-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0018_alter_chiefdashboard_year_alter_filtercondition_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filtercondition',
            unique_together=set(),
        ),
    ]
