# Generated by Django 5.1 on 2025-02-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0019_alter_filtercondition_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualplan',
            options={'verbose_name': 'Объемы: План на год', 'verbose_name_plural': 'Объемы: Планы на год'},
        ),
        migrations.AlterModelOptions(
            name='buildingplan',
            options={'verbose_name': 'Объемы: План корпуса', 'verbose_name_plural': 'Объемы: Планы корпусов'},
        ),
        migrations.AlterModelOptions(
            name='departmentplan',
            options={'verbose_name': 'Объемы: План отделения', 'verbose_name_plural': 'Объемы: Планы отделений'},
        ),
        migrations.AlterModelOptions(
            name='groupbuildingdepartment',
            options={'verbose_name': 'Корпус и отделение группы', 'verbose_name_plural': 'Объемы: Корпуса и отделения группы'},
        ),
        migrations.AlterModelOptions(
            name='groupindicators',
            options={'verbose_name': 'Объемы', 'verbose_name_plural': 'Объемы'},
        ),
        migrations.AlterModelOptions(
            name='monthlyplan',
            options={'verbose_name': 'Объемы: План на месяц', 'verbose_name_plural': 'Объемы: Планы на месяц'},
        ),
        migrations.AlterModelOptions(
            name='unifiedfilter',
            options={'verbose_name': 'Сверхподушевик', 'verbose_name_plural': 'Сверхподушевик'},
        ),
    ]
