# Generated by Django 5.1 on 2025-02-10 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_alter_doctorreportingrecord_doctor_records'),
        ('plan', '0020_alter_annualplan_options_alter_buildingplan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualDoctorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2025, verbose_name='Год')),
                ('doctor_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_doctor_plans', to='personnel.doctorreportingrecord', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'План на год для врача',
                'verbose_name_plural': 'Планы на год для врачей',
                'unique_together': {('doctor_record', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyDoctorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Бюджет')),
                ('annual_doctor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_doctor_plans', to='plan.annualdoctorplan', verbose_name='Годовой план для врача')),
            ],
            options={
                'verbose_name': 'Месячный план для врача',
                'verbose_name_plural': 'Месячные планы для врачей',
                'unique_together': {('annual_doctor_plan', 'month')},
            },
        ),
    ]
