# Generated by Django 5.1 on 2025-03-11 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0021_annualdoctorplan_monthlydoctorplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupindicators',
            name='departments',
        ),
    ]
