# Generated by Django 5.1 on 2025-05-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0022_remove_groupindicators_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalGroupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('groups', models.TextField(default='{}', help_text="Пример:\n{'Посещения': ['1','5','7','10'], 'Обращения':['30','301']}")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Группы целей для талонов врачей',
                'verbose_name_plural': 'Группы целей для талонов врачей',
            },
        ),
    ]
