# Generated by Django 5.1 on 2025-06-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0023_goalgroupconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualdoctorplan',
            name='department_plan',
            field=models.ForeignKey(blank=True, help_text='Связь с планом отделения для автоматического распределения', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_doctor_plans', to='plan.departmentplan', verbose_name='План отделения'),
        ),
        migrations.AddField(
            model_name='annualdoctorplan',
            name='is_auto_distributed',
            field=models.BooleanField(default=False, help_text='План автоматически распределен от отделения', verbose_name='Автоматическое распределение'),
        ),
    ]
