# Generated by Django 5.1 on 2025-10-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0024_annualdoctorplan_department_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualdoctorplan',
            name='department_plan',
        ),
        migrations.RemoveField(
            model_name='annualdoctorplan',
            name='is_auto_distributed',
        ),
        migrations.AddField(
            model_name='annualplan',
            name='show_in_cumulative_report',
            field=models.BooleanField(default=False, help_text="Отметьте, чтобы включить этот показатель в отчет 'Нарастающе по всем показателям'", verbose_name='Отображать в отчете нарастающе'),
        ),
    ]
