# Generated by Django 5.1 on 2025-11-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0025_remove_annualdoctorplan_department_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualplan',
            name='show_in_indicators_report',
            field=models.BooleanField(default=False, help_text="Отметьте, чтобы включить этот показатель в отчет 'Индикаторы'", verbose_name='Отображать в отчете индикаторов'),
        ),
    ]
