# Generated by Django 5.1 on 2025-11-05 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0026_annualplan_show_in_indicators_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualplan',
            name='external_id',
            field=models.CharField(blank=True, help_text='Уникальный идентификатор для синхронизации с базовым сервером', max_length=100, null=True, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='groupindicators',
            name='external_id',
            field=models.CharField(blank=True, help_text='Уникальный идентификатор для синхронизации с базовым сервером', max_length=100, null=True, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='groupindicators',
            name='sync_enabled',
            field=models.BooleanField(default=True, help_text='Включить эту группу в синхронизацию с клиентскими серверами', verbose_name='Синхронизировать'),
        ),
        migrations.CreateModel(
            name='OrganizationIndicatorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_code', models.CharField(blank=True, help_text='Код организации для которой этот показатель активен', max_length=100, null=True, verbose_name='Код организации')),
                ('is_enabled', models.BooleanField(default=True, help_text='Включить этот показатель для организации', verbose_name='Включен')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные примечания по использованию показателя', null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_configs', to='plan.groupindicators', verbose_name='Группа показателей')),
            ],
            options={
                'verbose_name': 'Конфигурация показателя организации',
                'verbose_name_plural': 'Конфигурации показателей организаций',
                'indexes': [models.Index(fields=['organization_code', 'is_enabled'], name='plan_organi_organiz_7bea4e_idx'), models.Index(fields=['group', 'organization_code'], name='plan_organi_group_i_46a837_idx')],
                'unique_together': {('group', 'organization_code')},
            },
        ),
    ]
