# Generated by Django 5.1 on 2025-11-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0027_annualplan_external_id_groupindicators_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtercondition',
            name='filter_type',
            field=models.CharField(choices=[('exact', 'Точное соответствие (=)'), ('in', 'В списке (IN)'), ('like', 'Похож на (LIKE)'), ('not_like', 'Не содержит (NOT LIKE)'), ('>', 'Больше (>)'), ('<', 'Меньше (<)'), ('>=', 'Больше или равно (>=)'), ('<=', 'Меньше или равно (<=)')], max_length=10, verbose_name='Тип фильтра'),
        ),
        migrations.AlterField(
            model_name='unifiedfiltercondition',
            name='filter_type',
            field=models.CharField(choices=[('exact', 'Точное соответствие (=)'), ('in', 'В списке (IN)'), ('like', 'Похож на (LIKE)'), ('not_like', 'Не содержит (NOT LIKE)'), ('<', 'Меньше (<)'), ('>', 'Больше (>)'), ('<=', 'Меньше или равно (<=)'), ('>=', 'Больше или равно (>=)')], max_length=10, verbose_name='Тип фильтра'),
        ),
    ]
