# Generated by Django 5.1 on 2025-11-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0028_alter_filtercondition_filter_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualplan',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, help_text='Порядок сортировки показателей при экспорте. Если пусто, используется иерархия групп.', null=True, verbose_name='Порядок сортировки'),
        ),
    ]
