# Generated by Django 5.1 on 2026-02-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0029_annualplan_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualdoctorplan',
            name='year',
            field=models.PositiveIntegerField(default=2026, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='chiefdashboard',
            name='year',
            field=models.IntegerField(default=2026, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='filtercondition',
            name='year',
            field=models.IntegerField(default=2026, verbose_name='Год действия фильтра'),
        ),
    ]
