# Generated by Django 5.1 on 2024-10-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DS168n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds', models.CharField(max_length=250, verbose_name='Диагноз')),
                ('profile', models.CharField(max_length=250, verbose_name='Профиль')),
                ('speciality', models.CharField(max_length=250, verbose_name='Специальность')),
                ('joint_speciality', models.CharField(max_length=250, verbose_name='Совместная специальность')),
            ],
            options={
                'verbose_name': 'Диагноз по 168н',
                'verbose_name_plural': 'Диагнозы по 168н',
            },
        ),
        migrations.CreateModel(
            name='ISZLDisNab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pID', models.CharField(max_length=255)),
                ('ldwID', models.CharField(max_length=255)),
                ('pdwID', models.CharField(max_length=255)),
                ('FIO', models.CharField(max_length=255)),
                ('DR', models.CharField(max_length=255)),
                ('DS', models.CharField(max_length=255)),
                ('DateBegin', models.CharField(max_length=255)),
                ('DateEnd', models.CharField(max_length=255)),
                ('idReason', models.CharField(max_length=255)),
                ('nameReason', models.CharField(max_length=255)),
                ('PlanMonth', models.CharField(max_length=255)),
                ('PlanYear', models.CharField(max_length=255)),
                ('FAM_D', models.CharField(max_length=255)),
                ('IM_D', models.CharField(max_length=255)),
                ('OT_D', models.CharField(max_length=255)),
                ('SS_D', models.CharField(max_length=255)),
                ('SPEC_D', models.CharField(max_length=255)),
                ('SpecV015', models.CharField(max_length=255)),
                ('DateInfo', models.CharField(max_length=255)),
                ('WayInfo', models.CharField(max_length=255)),
                ('ResInfo', models.CharField(max_length=255)),
                ('FactDN', models.CharField(max_length=255)),
                ('RezultDN', models.CharField(max_length=255)),
                ('ADR', models.CharField(max_length=255)),
                ('ENP', models.CharField(max_length=255)),
                ('LPU', models.CharField(max_length=255)),
                ('FIO_DOCTOR', models.CharField(max_length=255)),
                ('SS_DOCTOR', models.CharField(max_length=255)),
                ('LPUUCH', models.CharField(max_length=255)),
                ('SMO', models.CharField(max_length=255)),
                ('LPUAUTO', models.CharField(max_length=255)),
                ('LPUDT', models.CharField(max_length=255)),
                ('UserUpdateList', models.CharField(max_length=255)),
                ('DateUpdateList', models.CharField(max_length=255)),
                ('UserUpdatePlan', models.CharField(max_length=255)),
                ('DateUpdatePlan', models.CharField(max_length=255)),
                ('PeriodW', models.CharField(max_length=255)),
                ('DatePrev', models.CharField(max_length=255)),
                ('PlaceW', models.CharField(max_length=255)),
                ('w', models.CharField(max_length=255)),
                ('Column1', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ИСЗЛ: ДН',
                'verbose_name_plural': 'ИСЗЛ: ДН',
            },
        ),
        migrations.CreateModel(
            name='ISZLDisNabJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_iszl', models.CharField(max_length=255, verbose_name='id')),
                ('mo_prof', models.CharField(max_length=255, verbose_name='МО проф.м.')),
                ('mo_pri', models.CharField(max_length=255, verbose_name='МО прикрепления')),
                ('organization', models.CharField(max_length=255, verbose_name='Организация Проф.м.')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('fio', models.CharField(max_length=255, verbose_name='Ф.И.О.')),
                ('birth_date', models.CharField(max_length=255, verbose_name='Д.Р.')),
                ('enp', models.CharField(max_length=255, verbose_name='ЕНП')),
                ('ds', models.CharField(max_length=255, verbose_name='DS')),
                ('date', models.CharField(max_length=255, verbose_name='Дата')),
                ('time', models.CharField(max_length=255, verbose_name='Время')),
                ('info', models.CharField(max_length=255, verbose_name='Инф.')),
                ('fact', models.CharField(max_length=255, verbose_name='Факт')),
                ('smo', models.CharField(max_length=255, verbose_name='СМО')),
                ('modification_date_operator', models.CharField(max_length=255, verbose_name='Дата изм./Оператор')),
                ('column1', models.CharField(max_length=255, verbose_name='Column1')),
            ],
            options={
                'verbose_name': 'ИСЗЛ: ДН работающих',
                'verbose_name_plural': 'ИСЗЛ: ДН работающих',
            },
        ),
        migrations.CreateModel(
            name='ISZLPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.CharField(max_length=255)),
                ('FIO', models.CharField(max_length=255)),
                ('DR', models.CharField(max_length=255)),
                ('SMO', models.CharField(max_length=255)),
                ('ENP', models.CharField(max_length=255)),
                ('LPU', models.CharField(max_length=255)),
                ('SS_DOCTOR', models.CharField(max_length=255)),
                ('LPUUCH', models.CharField(max_length=255)),
                ('Upd', models.CharField(max_length=255)),
                ('CLOSED', models.CharField(max_length=255)),
                ('Column1', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ИСЗЛ: Прикрепленные',
                'verbose_name_plural': 'ИСЗЛ: Прикрепленных',
            },
        ),
        migrations.CreateModel(
            name='ISZLSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ИСЗЛ: Настройка',
                'verbose_name_plural': 'ИСЗЛ: Настройки',
            },
        ),
    ]
