# Generated by Django 5.1 on 2024-10-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0002_ds168n_iszldisnab_iszldisnabjob_iszlpeople_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Справочник: Категория данных', 'verbose_name_plural': 'Справочник: Категории данных'},
        ),
        migrations.AlterModelOptions(
            name='datatype',
            options={'verbose_name': 'Справочник: Тип данных', 'verbose_name_plural': 'Справочник: Типы данных'},
        ),
        migrations.AlterModelOptions(
            name='datatypefieldmapping',
            options={'verbose_name': 'Справочник: Соответствие полей', 'verbose_name_plural': 'Справочник: Соответствия полей'},
        ),
        migrations.AlterModelOptions(
            name='ds168n',
            options={'verbose_name': 'Справочник: Диагноз по 168н', 'verbose_name_plural': 'Справочник: Диагнозы по 168н'},
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='ADR',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='Column1',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='DR',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='DS',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='DateBegin',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='DateEnd',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='DateInfo',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='DatePrev',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='DateUpdateList',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='DateUpdatePlan',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='ENP',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='FAM_D',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='FIO',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='FIO_DOCTOR',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='FactDN',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='IM_D',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='LPU',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='LPUAUTO',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='LPUDT',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='LPUUCH',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='OT_D',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='PeriodW',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='PlaceW',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='PlanMonth',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='PlanYear',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='ResInfo',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='RezultDN',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='SMO',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='SPEC_D',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='SS_D',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='SS_DOCTOR',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='SpecV015',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='UserUpdateList',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='UserUpdatePlan',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='WayInfo',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='idReason',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='ldwID',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='nameReason',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='pID',
        ),
        migrations.RemoveField(
            model_name='iszldisnab',
            name='pdwID',
        ),
        migrations.RemoveField(
            model_name='iszlpeople',
            name='CLOSED',
        ),
        migrations.RemoveField(
            model_name='iszlpeople',
            name='Column1',
        ),
        migrations.RemoveField(
            model_name='iszlpeople',
            name='DR',
        ),
        migrations.RemoveField(
            model_name='iszlpeople',
            name='ENP',
        ),
        migrations.RemoveField(
            model_name='iszlpeople',
            name='FIO',
        ),
        migrations.RemoveField(
            model_name='iszlpeople',
            name='LPU',
        ),
        migrations.RemoveField(
            model_name='iszlpeople',
            name='LPUUCH',
        ),
        migrations.RemoveField(
            model_name='iszlpeople',
            name='PID',
        ),
        migrations.RemoveField(
            model_name='iszlpeople',
            name='SMO',
        ),
        migrations.RemoveField(
            model_name='iszlpeople',
            name='SS_DOCTOR',
        ),
        migrations.RemoveField(
            model_name='iszlpeople',
            name='Upd',
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='w',
            field=models.CharField(default='-', max_length=255, verbose_name='w'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='adr',
            field=models.CharField(default='-', max_length=255, verbose_name='ADR'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='column1',
            field=models.CharField(default='-', max_length=255, verbose_name='Column1'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='dr',
            field=models.CharField(default='-', max_length=255, verbose_name='DR'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='ds',
            field=models.CharField(default='-', max_length=255, verbose_name='DS'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='datebegin',
            field=models.CharField(default='-', max_length=255, verbose_name='DateBegin'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='dateend',
            field=models.CharField(default='-', max_length=255, verbose_name='DateEnd'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='dateinfo',
            field=models.CharField(default='-', max_length=255, verbose_name='DateInfo'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='dateprev',
            field=models.CharField(default='-', max_length=255, verbose_name='DatePrev'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='dateupdatelist',
            field=models.CharField(default='-', max_length=255, verbose_name='DateUpdateList'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='dateupdateplan',
            field=models.CharField(default='-', max_length=255, verbose_name='DateUpdatePlan'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='enp',
            field=models.CharField(default='-', max_length=255, verbose_name='ENP'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='fam_d',
            field=models.CharField(default='-', max_length=255, verbose_name='FAM_D'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='fio',
            field=models.CharField(default='-', max_length=255, verbose_name='FIO'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='fio_doctor',
            field=models.CharField(default='-', max_length=255, verbose_name='FIO_DOCTOR'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='factdn',
            field=models.CharField(default='-', max_length=255, verbose_name='FactDN'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='im_d',
            field=models.CharField(default='-', max_length=255, verbose_name='IM_D'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='lpu',
            field=models.CharField(default='-', max_length=255, verbose_name='LPU'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='lpuauto',
            field=models.CharField(default='-', max_length=255, verbose_name='LPUAUTO'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='lpudt',
            field=models.CharField(default='-', max_length=255, verbose_name='LPUDT'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='lpuuch',
            field=models.CharField(default='-', max_length=255, verbose_name='LPUUCH'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='ot_d',
            field=models.CharField(default='-', max_length=255, verbose_name='OT_D'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='periodw',
            field=models.CharField(default='-', max_length=255, verbose_name='PeriodW'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='placew',
            field=models.CharField(default='-', max_length=255, verbose_name='PlaceW'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='planmonth',
            field=models.CharField(default='-', max_length=255, verbose_name='PlanMonth'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='planyear',
            field=models.CharField(default='-', max_length=255, verbose_name='PlanYear'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='resinfo',
            field=models.CharField(default='-', max_length=255, verbose_name='ResInfo'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='rezultdn',
            field=models.CharField(default='-', max_length=255, verbose_name='RezultDN'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='smo',
            field=models.CharField(default='-', max_length=255, verbose_name='SMO'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='spec_d',
            field=models.CharField(default='-', max_length=255, verbose_name='SPEC_D'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='ss_d',
            field=models.CharField(default='-', max_length=255, verbose_name='SS_D'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='ss_doctor',
            field=models.CharField(default='-', max_length=255, verbose_name='SS_DOCTOR'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='specv015',
            field=models.CharField(default='-', max_length=255, verbose_name='SpecV015'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='userupdatelist',
            field=models.CharField(default='-', max_length=255, verbose_name='UserUpdateList'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='userupdateplan',
            field=models.CharField(default='-', max_length=255, verbose_name='UserUpdatePlan'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='wayinfo',
            field=models.CharField(default='-', max_length=255, verbose_name='WayInfo'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='idreason',
            field=models.CharField(default='-', max_length=255, verbose_name='idReason'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='ldwid',
            field=models.CharField(default='-', max_length=255, verbose_name='ldwID'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='namereason',
            field=models.CharField(default='-', max_length=255, verbose_name='nameReason'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='pid',
            field=models.CharField(default='-', max_length=255, verbose_name='pid'),
        ),
        migrations.AddField(
            model_name='iszldisnab',
            name='pdwid',
            field=models.CharField(default='-', max_length=255, verbose_name='pdwID'),
        ),
        migrations.AddField(
            model_name='iszlpeople',
            name='closed',
            field=models.CharField(default='-', max_length=255, verbose_name='CLOSED'),
        ),
        migrations.AddField(
            model_name='iszlpeople',
            name='column1',
            field=models.CharField(default='-', max_length=255, verbose_name='Column1'),
        ),
        migrations.AddField(
            model_name='iszlpeople',
            name='dr',
            field=models.CharField(default='-', max_length=255, verbose_name='DR'),
        ),
        migrations.AddField(
            model_name='iszlpeople',
            name='enp',
            field=models.CharField(default='-', max_length=255, verbose_name='ENP'),
        ),
        migrations.AddField(
            model_name='iszlpeople',
            name='fio',
            field=models.CharField(default='-', max_length=255, verbose_name='FIO'),
        ),
        migrations.AddField(
            model_name='iszlpeople',
            name='lpu',
            field=models.CharField(default='-', max_length=255, verbose_name='LPU'),
        ),
        migrations.AddField(
            model_name='iszlpeople',
            name='lpuuch',
            field=models.CharField(default='-', max_length=255, verbose_name='LPUUCH'),
        ),
        migrations.AddField(
            model_name='iszlpeople',
            name='pid',
            field=models.CharField(default='-', max_length=255, verbose_name='PID'),
        ),
        migrations.AddField(
            model_name='iszlpeople',
            name='smo',
            field=models.CharField(default='-', max_length=255, verbose_name='SMO'),
        ),
        migrations.AddField(
            model_name='iszlpeople',
            name='ss_doctor',
            field=models.CharField(default='-', max_length=255, verbose_name='SS_DOCTOR'),
        ),
        migrations.AddField(
            model_name='iszlpeople',
            name='upd',
            field=models.CharField(default='-', max_length=255, verbose_name='Upd'),
        ),
    ]
