# Generated by Django 5.1 on 2024-10-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0003_alter_category_options_alter_datatype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iszldisnab',
            name='adr',
            field=models.CharField(max_length=255, verbose_name='ADR'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='column1',
            field=models.CharField(max_length=255, verbose_name='Column1'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='datebegin',
            field=models.CharField(max_length=255, verbose_name='DateBegin'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='dateend',
            field=models.CharField(max_length=255, verbose_name='DateEnd'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='dateinfo',
            field=models.CharField(max_length=255, verbose_name='DateInfo'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='dateprev',
            field=models.CharField(max_length=255, verbose_name='DatePrev'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='dateupdatelist',
            field=models.CharField(max_length=255, verbose_name='DateUpdateList'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='dateupdateplan',
            field=models.CharField(max_length=255, verbose_name='DateUpdatePlan'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='dr',
            field=models.CharField(max_length=255, verbose_name='DR'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='ds',
            field=models.CharField(max_length=255, verbose_name='DS'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='enp',
            field=models.CharField(max_length=255, verbose_name='ENP'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='factdn',
            field=models.CharField(max_length=255, verbose_name='FactDN'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='fam_d',
            field=models.CharField(max_length=255, verbose_name='FAM_D'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='fio',
            field=models.CharField(max_length=255, verbose_name='FIO'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='fio_doctor',
            field=models.CharField(max_length=255, verbose_name='FIO_DOCTOR'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='idreason',
            field=models.CharField(max_length=255, verbose_name='idReason'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='im_d',
            field=models.CharField(max_length=255, verbose_name='IM_D'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='ldwid',
            field=models.CharField(max_length=255, verbose_name='ldwID'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='lpu',
            field=models.CharField(max_length=255, verbose_name='LPU'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='lpuauto',
            field=models.CharField(max_length=255, verbose_name='LPUAUTO'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='lpudt',
            field=models.CharField(max_length=255, verbose_name='LPUDT'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='lpuuch',
            field=models.CharField(max_length=255, verbose_name='LPUUCH'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='namereason',
            field=models.CharField(max_length=255, verbose_name='nameReason'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='ot_d',
            field=models.CharField(max_length=255, verbose_name='OT_D'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='pdwid',
            field=models.CharField(max_length=255, verbose_name='pdwID'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='periodw',
            field=models.CharField(max_length=255, verbose_name='PeriodW'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='placew',
            field=models.CharField(max_length=255, verbose_name='PlaceW'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='planmonth',
            field=models.CharField(max_length=255, verbose_name='PlanMonth'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='planyear',
            field=models.CharField(max_length=255, verbose_name='PlanYear'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='resinfo',
            field=models.CharField(max_length=255, verbose_name='ResInfo'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='rezultdn',
            field=models.CharField(max_length=255, verbose_name='RezultDN'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='smo',
            field=models.CharField(max_length=255, verbose_name='SMO'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='spec_d',
            field=models.CharField(max_length=255, verbose_name='SPEC_D'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='specv015',
            field=models.CharField(max_length=255, verbose_name='SpecV015'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='ss_d',
            field=models.CharField(max_length=255, verbose_name='SS_D'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='ss_doctor',
            field=models.CharField(max_length=255, verbose_name='SS_DOCTOR'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='userupdatelist',
            field=models.CharField(max_length=255, verbose_name='UserUpdateList'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='userupdateplan',
            field=models.CharField(max_length=255, verbose_name='UserUpdatePlan'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='w',
            field=models.CharField(max_length=255, verbose_name='w'),
        ),
        migrations.AlterField(
            model_name='iszldisnab',
            name='wayinfo',
            field=models.CharField(max_length=255, verbose_name='WayInfo'),
        ),
        migrations.AlterField(
            model_name='iszlpeople',
            name='closed',
            field=models.CharField(max_length=255, verbose_name='CLOSED'),
        ),
        migrations.AlterField(
            model_name='iszlpeople',
            name='column1',
            field=models.CharField(max_length=255, verbose_name='Column1'),
        ),
        migrations.AlterField(
            model_name='iszlpeople',
            name='dr',
            field=models.CharField(max_length=255, verbose_name='DR'),
        ),
        migrations.AlterField(
            model_name='iszlpeople',
            name='enp',
            field=models.CharField(max_length=255, verbose_name='ENP'),
        ),
        migrations.AlterField(
            model_name='iszlpeople',
            name='fio',
            field=models.CharField(max_length=255, verbose_name='FIO'),
        ),
        migrations.AlterField(
            model_name='iszlpeople',
            name='lpu',
            field=models.CharField(max_length=255, verbose_name='LPU'),
        ),
        migrations.AlterField(
            model_name='iszlpeople',
            name='lpuuch',
            field=models.CharField(max_length=255, verbose_name='LPUUCH'),
        ),
        migrations.AlterField(
            model_name='iszlpeople',
            name='pid',
            field=models.CharField(max_length=255, verbose_name='PID'),
        ),
        migrations.AlterField(
            model_name='iszlpeople',
            name='smo',
            field=models.CharField(max_length=255, verbose_name='SMO'),
        ),
        migrations.AlterField(
            model_name='iszlpeople',
            name='ss_doctor',
            field=models.CharField(max_length=255, verbose_name='SS_DOCTOR'),
        ),
        migrations.AlterField(
            model_name='iszlpeople',
            name='upd',
            field=models.CharField(max_length=255, verbose_name='Upd'),
        ),
    ]
