# Generated by Django 5.1 on 2024-10-09 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0004_alter_iszldisnab_adr_alter_iszldisnab_column1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLoaderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, verbose_name='Имя таблицы')),
                ('column_check', models.CharField(max_length=255, verbose_name='Столбец для проверки (после переименования)')),
                ('columns_for_update', models.TextField(help_text='Перечислите через запятую', verbose_name='Столбцы для обновления')),
                ('encoding', models.CharField(default='utf-8', max_length=50, verbose_name='Кодировка файла')),
                ('delimiter', models.CharField(default=';', max_length=10, verbose_name='Разделитель')),
                ('data_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_loader.datatype', verbose_name='Тип данных')),
            ],
        ),
    ]
