# Generated by Django 5.1 on 2024-10-15 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0006_alter_dataloaderconfig_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория ДН',
                'verbose_name_plural': 'Категории ДН',
            },
        ),
        migrations.AddField(
            model_name='ds168n',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_loader.categorydn', verbose_name='Категория ДН'),
        ),
    ]
