# Generated by Django 5.1 on 2024-10-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0008_kvazaremd_kvazarmedicalcertificate_kvazarmortality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvazarrecipe',
            name='er_status_details',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация по статусу отправки в 1ЭР'),
        ),
    ]
