# Generated by Django 5.1 on 2024-10-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0009_alter_kvazarrecipe_er_status_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvazarrecipe',
            name='remd_status_details',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация по статусу отправки в РЭМД'),
        ),
    ]
