# Generated by Django 5.1 on 2024-10-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0010_alter_kvazarrecipe_remd_status_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvazarmortality',
            name='initial_statistics_1',
            field=models.CharField(default=1, max_length=255, verbose_name='Первоначальная (статистика).1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kvazarmortality',
            name='issue_date_1',
            field=models.CharField(default=100, max_length=255, verbose_name='Дата выдачи.1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kvazarmortality',
            name='number_1',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер.1'),
            preserve_default=False,
        ),
    ]
