# Generated by Django 5.1 on 2024-10-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0011_kvazarmortality_initial_statistics_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iszldisnab',
            name='column1',
            field=models.CharField(default='-', max_length=255, verbose_name='Column1'),
        ),
        migrations.AlterField(
            model_name='iszldisnabjob',
            name='column1',
            field=models.CharField(default='-', max_length=255, verbose_name='Column1'),
        ),
        migrations.AlterField(
            model_name='iszlpeople',
            name='column1',
            field=models.CharField(default='-', max_length=255, verbose_name='Column1'),
        ),
    ]
