# Generated by Django 5.1 on 2024-10-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0012_alter_iszldisnab_column1_alter_iszldisnabjob_column1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omsdata',
            old_name='case',
            new_name='case_code',
        ),
    ]
