# Generated by Django 5.1 on 2024-11-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0013_rename_case_omsdata_case_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Итоговое сообщение'),
        ),
    ]
