# Generated by Django 5.1 on 2024-11-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0015_dataloaderconfig_clear_all_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='iszlsettings',
            name='password_people',
            field=models.CharField(default=1, max_length=255, verbose_name='Пароль ИСЗЛ:Население'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iszlsettings',
            name='user_people',
            field=models.CharField(default=100, max_length=255, verbose_name='Пользователь ИСЗЛ:Население'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iszlsettings',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль ИСЗЛ'),
        ),
        migrations.AlterField(
            model_name='iszlsettings',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Пользователь ИСЗЛ'),
        ),
    ]
