# Generated by Django 5.1 on 2024-11-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0018_doctordata_mo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordata',
            name='mo',
            field=models.CharField(default='-', max_length=255, verbose_name='МО'),
        ),
    ]
