# Generated by Django 5.1 on 2024-11-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0019_alter_doctordata_mo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordata',
            name='mo',
        ),
    ]
