# Generated by Django 5.1 on 2025-01-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0020_remove_doctordata_mo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='omsdata',
            constraint=models.UniqueConstraint(fields=('talon', 'source'), name='unique_talon_source'),
        ),
    ]
