# Generated by Django 5.1 on 2025-01-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0021_omsdata_unique_talon_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omsdata',
            name='account_number',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='additional_diagnosis',
            field=models.CharField(blank=True, default='-', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='additional_status_info',
            field=models.CharField(blank=True, default='-', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='age',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='amount',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='bed_profile',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='birth_date',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='care_conditions',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='case_code',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='classification_criterion',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='department',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='directing_mo',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='disease_type',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='dispensary_monitoring',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='doctor',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='doctor_profile',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='enp',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='federal_goal',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='gender',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='goal',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='home_visits',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='initial_input_date',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='insurance',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='ksg',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='kslp',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='kz',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='last_change_date',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='main_diagnosis',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='main_disease_character',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='medical_assistance_type',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='mo_visits',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='mp_profile',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='newborn',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='operator',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='outcome',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='paid',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='patient',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='payment_method_code',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='payment_source',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='payment_type',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='policy',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='report_period',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='representative',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='result',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='sanctions',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='shrm',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='smo_code',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='source',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='source_id',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='specialty',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='staff_position',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='status',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='talon_type',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='tariff',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='therapy_schema_code',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='treatment_end',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='treatment_start',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='uet',
            field=models.CharField(blank=True, default='-', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='upload_date',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='omsdata',
            name='visits',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
