# Generated by Django 5.1 on 2025-02-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0022_alter_omsdata_account_number_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detaileddata',
            constraint=models.UniqueConstraint(fields=('talon_number', 'service_code'), name='unique_talon_code'),
        ),
        migrations.AddConstraint(
            model_name='doctordata',
            constraint=models.UniqueConstraint(fields=('snils', 'doctor_code'), name='unique_snils_doctor_code'),
        ),
    ]
