# Generated by Django 5.1 on 2025-02-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0023_detaileddata_unique_talon_code_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='iszldisnab',
            constraint=models.UniqueConstraint(fields=('pdwid',), name='unique_pdwid_dn'),
        ),
        migrations.AddConstraint(
            model_name='iszldisnabjob',
            constraint=models.UniqueConstraint(fields=('id_iszl',), name='unique_id_iszl'),
        ),
        migrations.AddConstraint(
            model_name='iszlpeople',
            constraint=models.UniqueConstraint(fields=('pid',), name='unique_pid_people'),
        ),
    ]
