# Generated by Django 5.1 on 2025-02-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0024_iszldisnab_unique_pdwid_dn_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='iszlpeople',
            name='unique_pid_people',
        ),
        migrations.AddConstraint(
            model_name='iszlpeople',
            constraint=models.UniqueConstraint(fields=('enp',), name='unique_enp_people'),
        ),
    ]
