# Generated by Django 5.1 on 2025-04-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0025_remove_iszlpeople_unique_pid_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omsdata',
            name='additional_diagnosis',
            field=models.CharField(blank=True, default='-', max_length=1000, null=True),
        ),
    ]
