# Generated by Django 5.1 on 2025-11-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0026_alter_omsdata_additional_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvazarAnalysisOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
                ('lis', models.CharField(max_length=255, verbose_name='ЛИС')),
                ('patient', models.CharField(max_length=255, verbose_name='Пациент')),
                ('doctor', models.CharField(max_length=255, verbose_name='Врач')),
                ('operator', models.CharField(max_length=255, verbose_name='Оператор')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='Диагноз')),
                ('services', models.TextField(verbose_name='Услуги')),
                ('created_at', models.CharField(max_length=255, verbose_name='Создан')),
                ('payment_source', models.CharField(max_length=255, verbose_name='Источник оплаты')),
                ('emd_status', models.CharField(max_length=255, verbose_name='Статус ЭМД')),
                ('nns_vimis_status', models.CharField(max_length=255, verbose_name='Статус ННС ВИМИС')),
                ('rns_vimis_status', models.CharField(max_length=255, verbose_name='Статус (Р)НС ВИМИС')),
            ],
            options={
                'verbose_name': 'Квазар: Заказ анализа',
                'verbose_name_plural': 'Квазар: Заказы анализов',
                'db_table': 'load_data_analysis_orders',
            },
        ),
    ]
