# Generated by Django 5.1 on 2024-10-10 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oms_reference', '0002_statusweboms'),
        ('organization', '0003_medicalorganization_oid_mo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_text', models.CharField(max_length=255, verbose_name='Причина признания ЭМД не актуальным')),
            ],
            options={
                'verbose_name': 'Причина признания ЭМД не актуальным',
                'verbose_name_plural': 'Причины признания ЭМД не актуальными',
            },
        ),
        migrations.CreateModel(
            name='DeleteEmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_document', models.CharField(max_length=255, verbose_name='OID документа')),
                ('creation_date', models.DateTimeField(verbose_name='Дата создания')),
                ('registration_date', models.DateTimeField(verbose_name='Дата регистрации')),
                ('reestr_number', models.CharField(max_length=255, verbose_name='Номер в реестре РЭМД')),
                ('local_identifier', models.CharField(max_length=255, verbose_name='Локальный идентификатор')),
                ('document_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер документа, оформленного взамен')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('patient', models.CharField(max_length=255, verbose_name='Пациент')),
                ('date_of_birth', models.DateTimeField(verbose_name='Дата рождения')),
                ('enp', models.CharField(max_length=16, verbose_name='ЕНП')),
                ('treatment_end', models.DateTimeField(verbose_name='Окончание лечения')),
                ('goal', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='oms_reference.medicalorganizationomstarget', verbose_name='Цель ОМС')),
                ('oid_medical_organization', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organization.medicalorganization', verbose_name='OID Медицинской организации')),
                ('reason_not_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.invalidationreason', verbose_name='Причина признания ЭМД не актуальным')),
            ],
        ),
    ]
