# Generated by Django 5.1 on 2024-10-15 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_reference', '0002_statusweboms'),
        ('reports', '0002_alter_deleteemd_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteemd',
            name='creation_date',
            field=models.DateField(help_text='Журнал ЭМД: Дата документа', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='deleteemd',
            name='date_of_birth',
            field=models.DateField(help_text='Введите дату рождения пациента', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='deleteemd',
            name='document_number',
            field=models.CharField(blank=True, help_text='При наличии документа, выданного взамен. Журнал ЭМД: ИД', max_length=255, null=True, verbose_name='Номер документа, оформленного взамен'),
        ),
        migrations.AlterField(
            model_name='deleteemd',
            name='enp',
            field=models.CharField(help_text='Введите ЕНП пациента', max_length=16, verbose_name='ЕНП'),
        ),
        migrations.AlterField(
            model_name='deleteemd',
            name='goal',
            field=models.ForeignKey(help_text='Выберите актуальную цель ОМС', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='oms_reference.medicalorganizationomstarget', verbose_name='Цель ОМС'),
        ),
        migrations.AlterField(
            model_name='deleteemd',
            name='local_identifier',
            field=models.CharField(help_text='Журнал ЭМД:Сохранить документ в файл. Название файла xml при сохранении. Пример: 3e765e5d-acfc-4e44-b834-7a876acbe40c', max_length=255, verbose_name='Локальный идентификатор'),
        ),
        migrations.AlterField(
            model_name='deleteemd',
            name='oid_document',
            field=models.CharField(help_text='Идентификатор (OID) вида документа в 1.2.643.5.1.13.13.99.2.41', max_length=255, verbose_name='OID документа'),
        ),
        migrations.AlterField(
            model_name='deleteemd',
            name='patient',
            field=models.CharField(help_text='Введите ФИО пациента', max_length=255, verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='deleteemd',
            name='reason_not_actual',
            field=models.ForeignKey(help_text='Выберите причину аннулирования записи', on_delete=django.db.models.deletion.CASCADE, to='reports.invalidationreason', verbose_name='Причина признания ЭМД не актуальным'),
        ),
        migrations.AlterField(
            model_name='deleteemd',
            name='reestr_number',
            field=models.CharField(help_text='Журнал ЭМД: Регистрационный номер', max_length=255, verbose_name='Номер в реестре РЭМД'),
        ),
        migrations.AlterField(
            model_name='deleteemd',
            name='registration_date',
            field=models.DateField(help_text='Журнал ЭМД: Дата отправки в РИР.РЭМД', verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='deleteemd',
            name='treatment_end',
            field=models.DateField(help_text='Укажите дату завершения лечения', verbose_name='Окончание лечения'),
        ),
    ]
