# Generated by Django 5.1 on 2024-10-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_svomember_alter_deleteemd_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svomemberomsdata',
            name='treatment_end',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата окончания лечения'),
        ),
    ]
