# Generated by Django 5.1 on 2024-10-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_svomemberomsdata_treatment_end'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='svomember',
            options={'verbose_name': 'СВО: Участники', 'verbose_name_plural': 'СВО: Участники'},
        ),
        migrations.AlterModelOptions(
            name='svorelative',
            options={'verbose_name': 'СВО: Родственники', 'verbose_name_plural': 'СВО: Родственники'},
        ),
        migrations.AlterField(
            model_name='svomember',
            name='enp',
            field=models.CharField(max_length=16, verbose_name='ЕНП'),
        ),
        migrations.AddConstraint(
            model_name='svomember',
            constraint=models.UniqueConstraint(fields=('last_name', 'enp'), name='unique_last_name_enp'),
        ),
    ]
