# Generated by Django 5.1 on 2025-01-24 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_svomember_options_alter_svorelative_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100, verbose_name='Корпус')),
                ('site_name', models.CharField(max_length=100, verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
            },
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тип действия')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='reports.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Тип действия',
                'verbose_name_plural': 'Типы действий',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('enp', models.CharField(max_length=16, verbose_name='ЕНП')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('groups', models.ManyToManyField(blank=True, to='reports.group', verbose_name='Группы')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.site', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False, verbose_name='Выполнено?')),
                ('done_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата/время выполнения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.actiontype', verbose_name='Действие')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Выполнение действия',
                'verbose_name_plural': 'Выполнения действий',
                'ordering': ['-done_datetime'],
            },
        ),
    ]
