# Generated by Django 5.1 on 2025-01-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_group_site_actiontype_patient_patientaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actiontype',
            options={'verbose_name': 'Тип действия', 'verbose_name_plural': 'Реестр: Типы действий'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Реестр: группы'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['full_name'], 'verbose_name': 'Пациент', 'verbose_name_plural': 'Реестр: Пациенты'},
        ),
        migrations.AlterModelOptions(
            name='patientaction',
            options={'ordering': ['-done_datetime'], 'verbose_name': 'Выполнение действия', 'verbose_name_plural': 'Реестр: действия'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Участок', 'verbose_name_plural': 'Реестр: Участки'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='enp',
            field=models.CharField(max_length=20, unique=True, verbose_name='ЕНП'),
        ),
    ]
