# Generated by Django 5.1 on 2025-04-22 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_actiontype_options_alter_group_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_parent',
            field=models.BooleanField(default=False, verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='patient',
            name='parents',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_parent': True}, related_name='children', to='reports.patient', verbose_name='Родители'),
        ),
        migrations.CreateModel(
            name='DPChildDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(blank=True, max_length=200, verbose_name='Льгота')),
                ('drug', models.CharField(blank=True, max_length=200, verbose_name='Препарат')),
                ('remaining', models.PositiveIntegerField(blank=True, null=True, verbose_name='Остаток (таб)')),
                ('dose_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Дозировка в день (таб)')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего получения')),
                ('last_dose', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Дозировка в таблетках полученного в последний раз')),
                ('supply_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Обеспечение в днях')),
                ('intake_type', models.CharField(blank=True, max_length=20, verbose_name='Способ приёма')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dp_detail', to='reports.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Дети‑инвалиды ЛЛО: детали',
                'verbose_name_plural': 'Дети‑инвалиды ЛЛО: реестр',
            },
        ),
        migrations.CreateModel(
            name='UserGroupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.group', verbose_name='Группа пациента')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ пользователя к группе',
                'verbose_name_plural': 'Доступы пользователей к группам',
                'unique_together': {('user', 'group')},
            },
        ),
    ]
