# Generated by Django 5.1 on 2025-10-02 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_patient_is_parent_patient_parents_dpchilddetail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deleteemd',
            options={'ordering': ['-updated_at'], 'verbose_name': 'ЭМД: аннулирование', 'verbose_name_plural': 'ЭМД: аннулирование'},
        ),
        migrations.AddField(
            model_name='deleteemd',
            name='comment',
            field=models.TextField(blank=True, help_text='Дополнительные комментарии к заявке', null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='deleteemd',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='Пользователь, создавший заявку', on_delete=django.db.models.deletion.PROTECT, related_name='created_delete_emd', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteemd',
            name='responsible',
            field=models.ForeignKey(default=1, help_text='Пользователь, ответственный за заявку', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteemd',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('processed', 'Обработан'), ('rejected', 'Отклонен')], default='draft', help_text='Статус заявки на удаление ЭМД', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='deleteemd',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
