# Generated by Django 5.1 on 2025-10-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_deleteemd_options_deleteemd_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteemd',
            name='goal',
            field=models.CharField(help_text='Введите цель ОМС', max_length=255, verbose_name='Цель ОМС'),
        ),
        migrations.AlterField(
            model_name='deleteemd',
            name='responsible',
            field=models.CharField(help_text='Введите ФИО ответственного', max_length=255, verbose_name='Ответственный'),
        ),
    ]
