# Generated by Django 5.1 on 2025-10-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_alter_deleteemd_goal_alter_deleteemd_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteemd',
            name='sent_to_mz_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки в МЗ'),
        ),
    ]
