# Generated by Django 5.1 on 2025-11-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarLoadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=2, verbose_name='Код региона')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершена'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('records_loaded', models.IntegerField(default=0, verbose_name='Загружено записей')),
                ('records_total', models.IntegerField(blank=True, null=True, verbose_name='Всего записей')),
                ('source_file', models.CharField(blank=True, max_length=500, null=True, verbose_name='Исходный файл')),
                ('output_file', models.CharField(blank=True, max_length=500, null=True, verbose_name='Выходной файл')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало загрузки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание загрузки')),
            ],
            options={
                'verbose_name': 'История загрузки ГАР',
                'verbose_name_plural': 'История загрузок ГАР',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GarAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(db_index=True, max_length=2, verbose_name='Код региона')),
                ('area', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Район')),
                ('city', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Город')),
                ('settlement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Населенный пункт')),
                ('street', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Почтовый индекс')),
                ('full_address', models.TextField(blank=True, null=True, verbose_name='Полный адрес')),
                ('gar_object_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='ID объекта ГАР')),
                ('parent_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID родительского объекта')),
                ('object_level', models.IntegerField(blank=True, null=True, verbose_name='Уровень объекта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Адрес ГАР',
                'verbose_name_plural': 'Адреса ГАР',
                'indexes': [models.Index(fields=['region_code', 'city', 'street'], name='gar_garaddr_region__5967c2_idx'), models.Index(fields=['gar_object_id'], name='gar_garaddr_gar_obj_3ede53_idx'), models.Index(fields=['parent_id'], name='gar_garaddr_parent__949d82_idx')],
            },
        ),
    ]
