# Generated by Django 5.1 on 2025-12-18 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Тип участка',
                'verbose_name_plural': 'Типы участков',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(db_index=True, help_text='Формат: type/id (например, way/1386954792)', max_length=64, verbose_name='OSM ID')),
                ('osm_type', models.CharField(db_index=True, help_text='node, way или relation', max_length=16, verbose_name='Тип OSM объекта')),
                ('latitude', models.FloatField(db_index=True, verbose_name='Широта')),
                ('longitude', models.FloatField(db_index=True, verbose_name='Долгота')),
                ('housenumber', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Номер дома')),
                ('street', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Улица')),
                ('city', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Город')),
                ('postcode', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Почтовый индекс')),
                ('source', models.CharField(db_index=True, default='osm_export', help_text='Источник импорта: osm_export, pbf_import, manual и т.д.', max_length=64, verbose_name='Источник данных')),
                ('raw_tags', models.JSONField(blank=True, help_text='Дополнительные теги из OSM (если доступны)', null=True, verbose_name='Сырые теги OSM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ['city', 'street', 'housenumber'],
                'indexes': [models.Index(fields=['city', 'street', 'housenumber'], name='zones_addre_city_0d1133_idx'), models.Index(fields=['source'], name='zones_addre_source_a53e75_idx'), models.Index(fields=['latitude', 'longitude'], name='zones_addre_latitud_63d528_idx')],
                'constraints': [models.UniqueConstraint(fields=('osm_type', 'osm_id'), name='unique_osm_address')],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('polygon', models.JSONField(blank=True, help_text='Полигон в формате GeoJSON или массив координат [[lon, lat], ...]', null=True, verbose_name='Полигон')),
                ('color', models.CharField(blank=True, help_text='Цвет для отображения на карте, например #ff0000', max_length=16, verbose_name='Цвет')),
                ('area', models.FloatField(blank=True, help_text='Вычисляется автоматически при сохранении', null=True, verbose_name='Площадь (кв.м)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('code', models.CharField(db_index=True, help_text='Уникальный код организации', max_length=64, unique=True, verbose_name='Код')),
                ('metadata', models.JSONField(blank=True, help_text='Дополнительные параметры: удаленность, количество домов и т.д.', null=True, verbose_name='Метаданные')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='zones.address', verbose_name='Основной адрес')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('polygon', models.JSONField(blank=True, help_text='Полигон в формате GeoJSON или массив координат [[lon, lat], ...]', null=True, verbose_name='Полигон')),
                ('color', models.CharField(blank=True, help_text='Цвет для отображения на карте, например #ff0000', max_length=16, verbose_name='Цвет')),
                ('area', models.FloatField(blank=True, help_text='Вычисляется автоматически при сохранении', null=True, verbose_name='Площадь (кв.м)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('metadata', models.JSONField(blank=True, help_text='Дополнительные параметры: удаленность, количество домов и т.д.', null=True, verbose_name='Метаданные')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corpora', to='zones.address', verbose_name='Основной адрес')),
                ('organization', models.ForeignKey(help_text='Организация, к которой принадлежит корпус', on_delete=django.db.models.deletion.CASCADE, related_name='corpora', to='zones.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
                'ordering': ['organization', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('polygon', models.JSONField(blank=True, help_text='Полигон в формате GeoJSON или массив координат [[lon, lat], ...]', null=True, verbose_name='Полигон')),
                ('color', models.CharField(blank=True, help_text='Цвет для отображения на карте, например #ff0000', max_length=16, verbose_name='Цвет')),
                ('area', models.FloatField(blank=True, help_text='Вычисляется автоматически при сохранении', null=True, verbose_name='Площадь (кв.м)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('metadata', models.JSONField(blank=True, help_text='Дополнительные параметры: удаленность, количество домов и т.д.', null=True, verbose_name='Метаданные')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='zones.corpus', verbose_name='Корпус')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='zones.sitetype', verbose_name='Тип участка')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
                'ordering': ['corpus', 'type', 'name'],
                'unique_together': {('corpus', 'type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CorpusAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='main / branch / entrance и т.п.', max_length=32)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpus_links', to='zones.address')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='zones.corpus')),
            ],
            options={
                'verbose_name': 'Адрес корпуса',
                'verbose_name_plural': 'Адреса корпусов',
                'unique_together': {('corpus', 'address')},
            },
        ),
        migrations.CreateModel(
            name='SiteAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Привязан')),
                ('assigned_method', models.CharField(blank=True, help_text='auto / manual', max_length=16, verbose_name='Метод привязки')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_links', to='zones.address', verbose_name='Адрес')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_addresses', to='zones.site', verbose_name='Участок')),
                ('type', models.ForeignKey(help_text='Должен совпадать с типом участка (site.type)', on_delete=django.db.models.deletion.PROTECT, related_name='site_address_links', to='zones.sitetype', verbose_name='Тип участка')),
            ],
            options={
                'verbose_name': 'Привязка адреса к участку',
                'verbose_name_plural': 'Привязки адресов к участкам',
                'unique_together': {('address', 'type'), ('site', 'address')},
            },
        ),
    ]
