# Generated by Django 5.1 on 2025-12-18 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Привязан')),
                ('assigned_method', models.CharField(default='auto', help_text='auto / manual', max_length=16, verbose_name='Метод привязки')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='zones.address', verbose_name='Адрес')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_addresses', to='zones.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Привязка адреса к организации',
                'verbose_name_plural': 'Привязки адресов к организациям',
                'indexes': [models.Index(fields=['organization', 'assigned_at'], name='zones_organ_organiz_65a843_idx')],
                'unique_together': {('organization', 'address')},
            },
        ),
    ]
