# Generated by Django 5.1 on 2025-05-06 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_station_doctorassignment'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentperiod',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.station', verbose_name='Участок'),
        ),
    ]
