# Generated by Django 5.1 on 2025-05-28 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название льготной категории')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
            ],
            options={
                'verbose_name': 'Льготная категория',
                'verbose_name_plural': 'Льготные категории',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование ЛП')),
                ('inn', models.CharField(blank=True, max_length=255, null=True, verbose_name='МНН/форма выпуска/дозировка')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код ЛП')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
            ],
            options={
                'verbose_name': 'Лекарственный препарат',
                'verbose_name_plural': 'Лекарственные препараты',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО пациента')),
                ('birth_date', models.DateField(verbose_name='Дата рождения пациента')),
                ('snils', models.CharField(blank=True, max_length=20, null=True, verbose_name='СНИЛС пациента')),
                ('enp', models.CharField(blank=True, max_length=20, null=True, verbose_name='ЕНП пациента')),
                ('diagnosis_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код диагноза')),
                ('diagnosis_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название диагноза')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('benefit_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beneficiaries.benefitcategory', verbose_name='Льготная категория')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='DrugStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток (ед.)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='beneficiaries.drug', verbose_name='Лекарство')),
            ],
            options={
                'verbose_name': 'Остаток ЛП',
                'verbose_name_plural': 'Остатки ЛП',
                'unique_together': {('drug',)},
            },
        ),
        migrations.CreateModel(
            name='PatientDrugSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_need', models.CharField(max_length=50, verbose_name='Месячная потребность')),
                ('dose_regimen', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кратность приёма/дозы')),
                ('prescribed', models.CharField(blank=True, max_length=50, null=True, verbose_name='Выписано')),
                ('prescription_date', models.DateField(blank=True, null=True, verbose_name='Выписан рецепт')),
                ('supplied_until', models.DateField(blank=True, null=True, verbose_name='Обеспечен до')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_supplies', to='beneficiaries.drug', verbose_name='Лекарство')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_supplies', to='beneficiaries.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Обеспеченность пациента ЛП',
                'verbose_name_plural': 'Обеспеченность пациентов ЛП',
                'unique_together': {('patient', 'drug')},
            },
        ),
    ]
