# Generated by Django 5.1 on 2025-12-04 08:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefitcategory',
            options={'ordering': ['name'], 'verbose_name': 'Льготная категория', 'verbose_name_plural': 'Льготные категории'},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['name'], 'verbose_name': 'Лекарственный препарат', 'verbose_name_plural': 'Лекарственные препараты'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['full_name'], 'verbose_name': 'Пациент-льготник', 'verbose_name_plural': 'Пациенты-льготники'},
        ),
        migrations.AddField(
            model_name='benefitcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benefitcategory',
            name='default_coverage_percentage',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент покрытия по умолчанию'),
        ),
        migrations.AddField(
            model_name='benefitcategory',
            name='financing_source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Источник финансирования'),
        ),
        migrations.AddField(
            model_name='benefitcategory',
            name='is_for_children',
            field=models.BooleanField(default=False, verbose_name='Для детей'),
        ),
        migrations.AddField(
            model_name='benefitcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='drug',
            name='active_substance',
            field=models.CharField(blank=True, max_length=255, verbose_name='Действующее вещество'),
        ),
        migrations.AddField(
            model_name='drug',
            name='atc_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='АТХ код'),
        ),
        migrations.AddField(
            model_name='drug',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна производства'),
        ),
        migrations.AddField(
            model_name='drug',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Дозировка'),
        ),
        migrations.AddField(
            model_name='drug',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=100, verbose_name='Лекарственная форма'),
        ),
        migrations.AddField(
            model_name='drug',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='drug',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='patientdrugsupply',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО врача'),
        ),
        migrations.AddField(
            model_name='patientdrugsupply',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='patientdrugsupply',
            name='recipe_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер рецепта'),
        ),
        migrations.AddField(
            model_name='patientdrugsupply',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('active', 'Активно'), ('completed', 'Выполнено'), ('cancelled', 'Отменено'), ('expired', 'Истекло')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Код ЛП'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='benefit_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='beneficiaries.benefitcategory', verbose_name='Льготная категория'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='enp',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='ЕНП пациента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='snils',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='СНИЛС пациента'),
        ),
    ]
